-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Oct 05, 2024 at 06:21 AM
-- Server version: 10.4.25-MariaDB
-- PHP Version: 7.4.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `rayne`
--

-- --------------------------------------------------------

--
-- Table structure for table `cart`
--

CREATE TABLE `cart` (
  `id` bigint(10) NOT NULL,
  `user_id` varchar(60) NOT NULL,
  `product_id` bigint(10) NOT NULL,
  `product_name` varchar(100) NOT NULL,
  `product_price` bigint(10) NOT NULL,
  `size` varchar(10) NOT NULL,
  `quantity` bigint(10) NOT NULL,
  `product_description` varchar(200) NOT NULL,
  `product_category` varchar(40) NOT NULL,
  `company_name` varchar(100) NOT NULL,
  `product_varient_id` bigint(10) NOT NULL,
  `product_image` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------

--
-- Table structure for table `contact`
--

CREATE TABLE `contact` (
  `id` bigint(10) NOT NULL,
  `name` varchar(50) NOT NULL,
  `email` varchar(90) NOT NULL,
  `subject` varchar(300) NOT NULL,
  `messege` varchar(1000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `contact`
--

INSERT INTO `contact` (`id`, `name`, `email`, `subject`, `messege`) VALUES
(1, 'Sahin nayak', 'nayak02@gmail.com', 'dasdasd', 'sadwada');

-- --------------------------------------------------------

--
-- Table structure for table `customer_details`
--

CREATE TABLE `customer_details` (
  `c_name` varchar(100) NOT NULL,
  `c_phone` bigint(11) NOT NULL,
  `c_email` varchar(70) NOT NULL,
  `c_password` varchar(100) NOT NULL,
  `category` varchar(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `customer_details`
--

INSERT INTO `customer_details` (`c_name`, `c_phone`, `c_email`, `c_password`, `category`) VALUES
('Tapas Dalui', 9087654565, 'daluitapas@gmail.com', '$2y$10$qlmDfDraErAcO0Btm9hnFOsFOnQiqdm2RVTGuonAgpW3DZBAYz1Im', 'user'),
('Sahin', 8336890358, 'nayaksahin2002@gmail.com', '$2y$10$s0YGBBZc7.ptU1VdK19zWuXrYBK6TWFVfbMqwp9MKjWFFB/AoDVzG', 'admin'),
('Subhrajyoti Sarkar', 9494949494, 'subhra@gmail.com', '$2y$10$N.fjIyYUtaXCTj1Te6VZTehZ4RrxAKyziA0zy5kA2HEpMjUnJW462', 'admin');

-- --------------------------------------------------------

--
-- Table structure for table `customer_orders`
--

CREATE TABLE `customer_orders` (
  `id` bigint(10) NOT NULL,
  `user_id` varchar(60) NOT NULL,
  `product_id` bigint(10) NOT NULL,
  `product_name` varchar(100) NOT NULL,
  `product_price` bigint(19) NOT NULL,
  `size` varchar(10) NOT NULL,
  `quantity` bigint(10) NOT NULL,
  `product_description` varchar(200) NOT NULL,
  `product_category` varchar(19) NOT NULL,
  `company_name` varchar(100) NOT NULL,
  `product_varient_id` bigint(10) NOT NULL,
  `product_image` varchar(100) NOT NULL,
  `bill_id` bigint(100) NOT NULL,
  `bill_date` varchar(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `customer_orders`
--

INSERT INTO `customer_orders` (`id`, `user_id`, `product_id`, `product_name`, `product_price`, `size`, `quantity`, `product_description`, `product_category`, `company_name`, `product_varient_id`, `product_image`, `bill_id`, `bill_date`) VALUES
(5, 'daluitapas@gmail.com', 1, 'Scott International Shirt for Men, Solid Full Sleeves Shirt, Wrinkle Free Mens Shirts, Cotton Formal', 799, 'XXL', 1, 'Material composition Fil-A-Fil cotton <br>\r\nPattern Solid <br>\r\nFit type Regular Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Collared neck <br>\r\nLength Standard Length <br>\r\nCountry of Origin', 'shirt', 'Scott International', 1, 'https://m.media-amazon.com/images/I/61AYhFbHD1L._SX466_.jpg', 413, '2024-09-15'),
(6, 'daluitapas@gmail.com', 17, 'CB-COLEBROOK Mens Casual Button Down Shirts Long Sleeve Linen Shirt Fashion Textured Beach Summer', 499, 'XXL', 1, 'Material composition Soft, Breathable and Light Fabric <br>\r\nFit type Regular Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Spread Collar <br>\r\nLength Standard Length <br>\r\nNeck style Collared ', 'shirt', 'CB-COLEBROOK Store', 3, 'https://m.media-amazon.com/images/I/51fVQasKeNL._SY500_.jpg', 413, '2024-09-15'),
(7, 'daluitapas@gmail.com', 54, 'BULLMER Black Trendy Front and Back Printed oversized Round Neck T-shirt for men', 299, 'XL', 2, 'Material composition Cottonblend <br>\r\nPattern Printed <br>\r\nFit type Regular Fit <br>\r\nSleeve type Half Sleeve <br>\r\nCollar style Club Collar <br>\r\nLength Standard Length <br>\r\nCountry of Origin Indi', 't-shirt', 'BULLMER Store', 12, 'https://m.media-amazon.com/images/I/71FxA9LOV1L._SX466_.jpg', 282, '2024-09-15'),
(9, 'daluitapas@gmail.com', 135, 'DSK Studio Women Short Kurti', 242, 'XXL', 1, 'Material type Organza,Crepe,Polyester <br>\r\nFit type Regular <br>\r\nStyle Regular <br>\r\nClosure type Pull On <br>\r\nCare instructions Machine Wash <br>\r\nAge range description Adult <br>\r\nCountry of Orig', 'kurti', 'DSK Studio', 35, 'https://m.media-amazon.com/images/I/8136v9EIK4L._SY550_.jpg', 606, '2024-09-15');

-- --------------------------------------------------------

--
-- Table structure for table `product_details`
--

CREATE TABLE `product_details` (
  `product_id` bigint(9) NOT NULL,
  `product_name` varchar(100) NOT NULL,
  `product_price` bigint(10) NOT NULL,
  `product_description` varchar(200) NOT NULL,
  `product_category` varchar(30) NOT NULL,
  `product_gender` varchar(10) NOT NULL,
  `company_name` varchar(100) NOT NULL,
  `product_image` varchar(100) NOT NULL,
  `product_varient_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `product_details`
--

INSERT INTO `product_details` (`product_id`, `product_name`, `product_price`, `product_description`, `product_category`, `product_gender`, `company_name`, `product_image`, `product_varient_id`) VALUES
(1, 'Scott International Shirt for Men, Solid Full Sleeves Shirt, Wrinkle Free Mens Shirts, Cotton Formal', 799, 'Material composition Fil-A-Fil cotton <br>\r\nPattern Solid <br>\r\nFit type Regular Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Collared neck <br>\r\nLength Standard Length <br>\r\nCountry of Origin', 'shirt', 'men', 'Scott International', 'https://m.media-amazon.com/images/I/61AYhFbHD1L._SX466_.jpg', 1),
(2, 'Scott International Shirt for Men, Solid Full Sleeves Shirt, Wrinkle Free Mens Shirts, Cotton Formal', 799, 'Material composition Fil-A-Fil cotton <br>\r\nPattern Solid <br>\r\nFit type Regular Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Collared neck <br>\r\nLength Standard Length <br>\r\nCountry of Origin', 'shirt', 'men', 'Scott International', 'https://m.media-amazon.com/images/I/51SwZk6Na-L._SX466_.jpg', 1),
(3, 'Scott International Shirt for Men, Solid Full Sleeves Shirt, Wrinkle Free Mens Shirts, Cotton Formal', 799, 'Material composition Fil-A-Fil cotton <br>\r\nPattern Solid <br>\r\nFit type Regular Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Collared neck <br>\r\nLength Standard Length <br>\r\nCountry of Origin', 'shirt', 'men', 'Scott International', 'https://m.media-amazon.com/images/I/51X5JPMP1BL._SY550_.jpg', 1),
(4, 'Scott International Shirt for Men, Solid Full Sleeves Shirt, Wrinkle Free Mens Shirts, Cotton Formal', 799, 'Material composition Fil-A-Fil cotton <br>\r\nPattern Solid <br>\r\nFit type Regular Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Collared neck <br>\r\nLength Standard Length <br>\r\nCountry of Origin', 'shirt', 'men', 'Scott International', 'https://m.media-amazon.com/images/I/51NDd6CIBTL._SX466_.jpg', 1),
(5, 'Scott International Shirt for Men, Solid Full Sleeves Shirt, Wrinkle Free Mens Shirts, Cotton Formal', 799, 'Material composition Fil-A-Fil cotton <br>\r\nPattern Solid <br>\r\nFit type Regular Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Collared neck <br>\r\nLength Standard Length <br>\r\nCountry of Origin', 'shirt', 'men', 'Scott International', 'https://m.media-amazon.com/images/I/61jNjmgh-SL._SX466_.jpg', 1),
(6, 'Scott International Shirt for Men, Solid Full Sleeves Shirt, Wrinkle Free Mens Shirts, Cotton Formal', 799, 'Material composition Fil-A-Fil cotton <br>\r\nPattern Solid <br>\r\nFit type Regular Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Collared neck <br>\r\nLength Standard Length <br>\r\nCountry of Origin', 'shirt', 'men', 'Scott International', 'https://m.media-amazon.com/images/I/6192LNjOcNL._SX466_.jpg', 1),
(7, 'FIFTH ANFOLD Mens Cotton Full Sleeve Regular Fit Collared Neck Casual Shirt for men, Office wear', 799, 'Material composition Pure Cotton <br>\r\nPattern Solid <br>\r\nFit type Slim Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Club Collar <br>\r\nLength Standard Length <br>\r\nCountry of Origin India <br', 'shirt', 'men', 'FIFTH ANFOLD', 'https://m.media-amazon.com/images/I/31G6ruw6QWL.jpg', 2),
(8, 'FIFTH ANFOLD Mens Cotton Full Sleeve Regular Fit Collared Neck Casual Shirt for men, Office wear', 799, 'Material composition Pure Cotton <br>\r\nPattern Solid <br>\r\nFit type Slim Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Club Collar <br>\r\nLength Standard Length <br>\r\nCountry of Origin India <br', 'shirt', 'men', 'FIFTH ANFOLD', 'https://m.media-amazon.com/images/I/817btHL8obL._SX425_.jpg', 2),
(9, 'FIFTH ANFOLD Mens Cotton Full Sleeve Regular Fit Collared Neck Casual Shirt for men, Office wear', 799, 'Material composition Pure Cotton <br>\r\nPattern Solid <br>\r\nFit type Slim Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Club Collar <br>\r\nLength Standard Length <br>\r\nCountry of Origin India <br', 'shirt', 'men', 'FIFTH ANFOLD', 'https://m.media-amazon.com/images/I/31Pmbs+wPWL.jpg', 2),
(10, 'FIFTH ANFOLD Mens Cotton Full Sleeve Regular Fit Collared Neck Casual Shirt for men, Office wear', 799, 'Material composition Pure Cotton <br>\r\nPattern Solid <br>\r\nFit type Slim Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Club Collar <br>\r\nLength Standard Length <br>\r\nCountry of Origin India <br', 'shirt', 'men', 'FIFTH ANFOLD', 'https://m.media-amazon.com/images/I/41LWvsza8VL.jpg', 2),
(11, 'FIFTH ANFOLD Mens Cotton Full Sleeve Regular Fit Collared Neck Casual Shirt for men, Office wear', 799, 'Material composition Pure Cotton <br>\r\nPattern Solid <br>\r\nFit type Slim Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Club Collar <br>\r\nLength Standard Length <br>\r\nCountry of Origin India <br', 'shirt', 'men', 'FIFTH ANFOLD', 'https://m.media-amazon.com/images/I/819WXn1OY+L._SX425_.jpg', 2),
(12, 'FIFTH ANFOLD Mens Cotton Full Sleeve Regular Fit Collared Neck Casual Shirt for men, Office wear', 799, 'Material composition Pure Cotton <br>\r\nPattern Solid <br>\r\nFit type Slim Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Club Collar <br>\r\nLength Standard Length <br>\r\nCountry of Origin India <br', 'shirt', 'men', 'FIFTH ANFOLD', 'https://m.media-amazon.com/images/I/41FPpsqWYmL.jpg', 2),
(13, 'CB-COLEBROOK Mens Casual Button Down Shirts Long Sleeve Linen Shirt Fashion Textured Beach Summer', 499, 'Material composition Soft, Breathable and Light Fabric <br>\r\nFit type Regular Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Spread Collar <br>\r\nLength Standard Length <br>\r\nNeck style Collared ', 'shirt', 'men', 'CB-COLEBROOK Store', 'https://m.media-amazon.com/images/I/51-pLhPHoBL._SY500_.jpg', 3),
(14, 'CB-COLEBROOK Mens Casual Button Down Shirts Long Sleeve Linen Shirt Fashion Textured Beach Summer', 499, 'Material composition Soft, Breathable and Light Fabric <br>\r\nFit type Regular Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Spread Collar <br>\r\nLength Standard Length <br>\r\nNeck style Collared ', 'shirt', 'men', 'CB-COLEBROOK Store', 'https://m.media-amazon.com/images/I/51RgKA1pC1L._SY500_.jpg', 3),
(15, 'CB-COLEBROOK Mens Casual Button Down Shirts Long Sleeve Linen Shirt Fashion Textured Beach Summer', 499, 'Material composition Soft, Breathable and Light Fabric <br>\r\nFit type Regular Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Spread Collar <br>\r\nLength Standard Length <br>\r\nNeck style Collared ', 'shirt', 'men', 'CB-COLEBROOK Store', 'https://m.media-amazon.com/images/I/510EN5eXNPL._SY500_.jpg', 3),
(16, 'CB-COLEBROOK Mens Casual Button Down Shirts Long Sleeve Linen Shirt Fashion Textured Beach Summer', 499, 'Material composition Soft, Breathable and Light Fabric <br>\r\nFit type Regular Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Spread Collar <br>\r\nLength Standard Length <br>\r\nNeck style Collared ', 'shirt', 'men', 'CB-COLEBROOK Store', 'https://m.media-amazon.com/images/I/51STJxwM9KL._SY500_.jpg', 3),
(17, 'CB-COLEBROOK Mens Casual Button Down Shirts Long Sleeve Linen Shirt Fashion Textured Beach Summer', 499, 'Material composition Soft, Breathable and Light Fabric <br>\r\nFit type Regular Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Spread Collar <br>\r\nLength Standard Length <br>\r\nNeck style Collared ', 'shirt', 'men', 'CB-COLEBROOK Store', 'https://m.media-amazon.com/images/I/51fVQasKeNL._SY500_.jpg', 3),
(18, 'CB-COLEBROOK Mens Casual Button Down Shirts Long Sleeve Linen Shirt Fashion Textured Beach Summer', 499, 'Material composition Soft, Breathable and Light Fabric <br>\r\nFit type Regular Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Spread Collar <br>\r\nLength Standard Length <br>\r\nNeck style Collared ', 'shirt', 'men', 'CB-COLEBROOK Store', 'https://m.media-amazon.com/images/I/51OPKz-47kL._SY500_.jpg', 3),
(19, 'Bellstone Mens Solid Regular Fit Dress Shirt', 489, 'Material composition Cotton Blend <br>\r\nSleeve type Long Sleeve <br>\r\nLength Waist length <br>\r\nNeck style Collared Neck <br>\r\nPattern Solid <br>\r\nStyle Regular <br>\r\nCountry of Origin India <br>', 'shirt', 'men', 'Bellstone', 'https://m.media-amazon.com/images/I/61NloRw77IL._SY550_.jpg', 4),
(20, 'Bellstone Mens Solid Regular Fit Dress Shirt', 489, 'Material composition Cotton Blend <br>\r\nSleeve type Long Sleeve <br>\r\nLength Waist length <br>\r\nNeck style Collared Neck <br>\r\nPattern Solid <br>\r\nStyle Regular <br>\r\nCountry of Origin India <br>', 'shirt', 'men', 'Bellstone', 'https://m.media-amazon.com/images/I/61GV8czA4kL._SY550_.jpg', 4),
(21, 'Bellstone Mens Solid Regular Fit Dress Shirt', 489, 'Material composition Cotton Blend <br>\r\nSleeve type Long Sleeve <br>\r\nLength Waist length <br>\r\nNeck style Collared Neck <br>\r\nPattern Solid <br>\r\nStyle Regular <br>\r\nCountry of Origin India <br>', 'shirt', 'men', 'Bellstone', 'https://m.media-amazon.com/images/I/61zay4O3DML._SY550_.jpg', 4),
(22, 'Bellstone Mens Solid Regular Fit Dress Shirt', 489, 'Material composition Cotton Blend <br>\r\nSleeve type Long Sleeve <br>\r\nLength Waist length <br>\r\nNeck style Collared Neck <br>\r\nPattern Solid <br>\r\nStyle Regular <br>\r\nCountry of Origin India <br>', 'shirt', 'men', 'Bellstone', 'https://m.media-amazon.com/images/I/61klmuSDQ6L._SY550_.jpg', 4),
(23, 'Bellstone Mens Solid Regular Fit Dress Shirt', 489, 'Material composition Cotton Blend <br>\r\nSleeve type Long Sleeve <br>\r\nLength Waist length <br>\r\nNeck style Collared Neck <br>\r\nPattern Solid <br>\r\nStyle Regular <br>\r\nCountry of Origin India <br>', 'shirt', 'men', 'Bellstone', 'https://m.media-amazon.com/images/I/61XxXr0Tg7L._SY550_.jpg', 4),
(26, 'Lymio Casual Shirt for Men|| Shirt for Men|| Men Stylish Shirt (Rib-Shirt)', 479, 'Material composition Polyester <br>\r\nPattern Solid <br>\r\nFit type Regular Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Collared Neck <br>\r\nLength Standard Length <br>\r\nCountry of Origin India ', 'shirt', 'men', 'Lymio Casual Shirt for Men|| Shirt for Men|| Men Stylish Shirt (Rib-Shirt)', 'https://m.media-amazon.com/images/I/71V5gEc8YVL._SY550_.jpg', 5),
(27, 'Lymio Casual Shirt for Men|| Shirt for Men|| Men Stylish Shirt (Rib-Shirt)', 479, 'Material composition Polyester <br>\r\nPattern Solid <br>\r\nFit type Regular Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Collared Neck <br>\r\nLength Standard Length <br>\r\nCountry of Origin India ', 'shirt', 'men', 'Lymio Casual Shirt for Men|| Shirt for Men|| Men Stylish Shirt (Rib-Shirt)', 'https://m.media-amazon.com/images/I/71kE75JMKjL._SY550_.jpg', 5),
(28, 'Lymio Casual Shirt for Men|| Shirt for Men|| Men Stylish Shirt (Rib-Shirt)', 479, 'Material composition Polyester <br>\r\nPattern Solid <br>\r\nFit type Regular Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Collared Neck <br>\r\nLength Standard Length <br>\r\nCountry of Origin India ', 'shirt', 'men', 'Lymio Casual Shirt for Men|| Shirt for Men|| Men Stylish Shirt (Rib-Shirt)', 'https://m.media-amazon.com/images/I/71cc5ovpHqL._SY550_.jpg', 5),
(29, 'Dennis Lingo Men Checkered Slim Fit Cotton Casual Shirt', 611, 'Material composition 100% Cotton <br>\r\nPattern Checkered <br>\r\nFit type Slim Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Spread Collar <br>\r\nLength Standard Length <br>\r\nCountry of Origin Ind', 'shirt', 'men', 'Dennis Lingo Store\r\n', 'https://m.media-amazon.com/images/I/61DGAlvxRLL._SY550_.jpg', 6),
(30, 'Dennis Lingo Men Checkered Slim Fit Cotton Casual Shirt', 573, 'Material composition 100% Cotton <br>\r\nPattern Checkered <br>\r\nFit type Slim Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Spread Collar <br>\r\nLength Standard Length <br>\r\nCountry of Origin Ind', 'shirt', 'men', 'Dennis Lingo Store\r\n', 'https://m.media-amazon.com/images/I/71e-5LUOFsL._SX522_.jpg', 7),
(31, 'TURMS Anti Stain Anti Odor Polo T Shirt for Men | Water Repellent | Stretchable T Shirt for Boys | R', 1852, 'Material composition 95% Premium Cotton and 5% Elastane <br>\r\nPattern Solid <br>\r\nFit type Slim Fit <br>\r\nSleeve type Half Sleeve <br>\r\nCollar style Spread Collar <br>\r\nLength Standard Length <br>\r\nCo', 't-shirt', 'men', 'TURMS Store', 'https://m.media-amazon.com/images/I/71QFM4zOC0L._SX466_.jpg', 8),
(32, 'TURMS Anti Stain Anti Odor Polo T Shirt for Men | Water Repellent | Stretchable T Shirt for Boys | R', 1852, 'Material composition 95% Premium Cotton and 5% Elastane <br>\r\nPattern Solid <br>\r\nFit type Slim Fit <br>\r\nSleeve type Half Sleeve <br>\r\nCollar style Spread Collar <br>\r\nLength Standard Length <br>\r\nCo', 't-shirt', 'men', 'TURMS Store', 'https://m.media-amazon.com/images/I/41PRaaoSEuL._SY550_.jpg', 8),
(33, 'TURMS Anti Stain Anti Odor Polo T Shirt for Men | Water Repellent | Stretchable T Shirt for Boys | R', 1852, 'Material composition 95% Premium Cotton and 5% Elastane <br>\r\nPattern Solid <br>\r\nFit type Slim Fit <br>\r\nSleeve type Half Sleeve <br>\r\nCollar style Spread Collar <br>\r\nLength Standard Length <br>\r\nCo', 't-shirt', 'men', 'TURMS Store', 'https://m.media-amazon.com/images/I/71go2CV-YCL._SY550_.jpg', 8),
(34, 'TURMS Anti Stain Anti Odor Polo T Shirt for Men | Water Repellent | Stretchable T Shirt for Boys | R', 1852, 'Material composition 95% Premium Cotton and 5% Elastane <br>\r\nPattern Solid <br>\r\nFit type Slim Fit <br>\r\nSleeve type Half Sleeve <br>\r\nCollar style Spread Collar <br>\r\nLength Standard Length <br>\r\nCo', 't-shirt', 'men', 'TURMS Store', 'https://m.media-amazon.com/images/I/81F-N2xiDRL._SY550_.jpg', 8),
(35, 'TURMS Anti Stain Anti Odor Polo T Shirt for Men | Water Repellent | Stretchable T Shirt for Boys | R', 1852, 'Material composition 95% Premium Cotton and 5% Elastane <br>\r\nPattern Solid <br>\r\nFit type Slim Fit <br>\r\nSleeve type Half Sleeve <br>\r\nCollar style Spread Collar <br>\r\nLength Standard Length <br>\r\nCo', 't-shirt', 'men', 'TURMS Store', 'https://m.media-amazon.com/images/I/41an-FuY1tL._SY550_.jpg', 8),
(36, 'TURMS Anti Stain Anti Odor Polo T Shirt for Men | Water Repellent | Stretchable T Shirt for Boys | R', 1852, 'Material composition 95% Premium Cotton and 5% Elastane <br>\r\nPattern Solid <br>\r\nFit type Slim Fit <br>\r\nSleeve type Half Sleeve <br>\r\nCollar style Spread Collar <br>\r\nLength Standard Length <br>\r\nCo', 't-shirt', 'men', 'TURMS Store', 'https://m.media-amazon.com/images/I/717-NN8T+3L._SX466_.jpg', 8),
(37, 'Amazon Brand - Symbol Men Cotton Rich Polo T Shirt | Collar Tshirts | Half Sleeves | Plain-Regular', 399, 'Material composition 60% Cotton, 40% Polyester <br>\r\nPattern Solid <br>\r\nFit type Regular Fit <br>\r\nSleeve type Short Sleeve <br>\r\nCollar style Classic Collar <br>\r\nLength Standard Length <br>\r\nCountr', 't-shirt', 'men', 'Amazon Brand - Symbol Store', 'https://m.media-amazon.com/images/I/713n+TxyfCL._SY550_.jpg', 9),
(38, 'Amazon Brand - Symbol Men Cotton Rich Polo T Shirt | Collar Tshirts | Half Sleeves | Plain-Regular', 399, 'Material composition 60% Cotton, 40% Polyester <br>\r\nPattern Solid <br>\r\nFit type Regular Fit <br>\r\nSleeve type Short Sleeve <br>\r\nCollar style Classic Collar <br>\r\nLength Standard Length <br>\r\nCountr', 't-shirt', 'men', 'Amazon Brand - Symbol Store', 'https://m.media-amazon.com/images/I/81h32NQvVuL._SY550_.jpg', 9),
(39, 'Amazon Brand - Symbol Men Cotton Rich Polo T Shirt | Collar Tshirts | Half Sleeves | Plain-Regular', 399, 'Material composition 60% Cotton, 40% Polyester <br>\r\nPattern Solid <br>\r\nFit type Regular Fit <br>\r\nSleeve type Short Sleeve <br>\r\nCollar style Classic Collar <br>\r\nLength Standard Length <br>\r\nCountr', 't-shirt', 'men', 'Amazon Brand - Symbol Store', 'https://m.media-amazon.com/images/I/81Du0iT+WDL._SY550_.jpg', 8),
(40, 'Amazon Brand - Symbol Men Cotton Rich Polo T Shirt | Collar Tshirts | Half Sleeves | Plain-Regular', 399, 'Material composition 60% Cotton, 40% Polyester <br>\r\nPattern Solid <br>\r\nFit type Regular Fit <br>\r\nSleeve type Short Sleeve <br>\r\nCollar style Classic Collar <br>\r\nLength Standard Length <br>\r\nCountr', 't-shirt', 'men', 'Amazon Brand - Symbol Store', 'https://m.media-amazon.com/images/I/81xbkxEVMUL._SY550_.jpg', 9),
(41, 'Amazon Brand - Symbol Men Cotton Rich Polo T Shirt | Collar Tshirts | Half Sleeves | Plain-Regular', 399, 'Material composition 60% Cotton, 40% Polyester <br>\r\nPattern Solid <br>\r\nFit type Regular Fit <br>\r\nSleeve type Short Sleeve <br>\r\nCollar style Classic Collar <br>\r\nLength Standard Length <br>\r\nCountr', 't-shirt', 'men', 'Amazon Brand - Symbol Store', 'https://m.media-amazon.com/images/I/81QaUlUAv4L._SY550_.jpg', 9),
(42, 'Amazon Brand - Symbol Men Cotton Rich Polo T Shirt | Collar Tshirts | Half Sleeves | Plain-Regular', 399, 'Material composition 60% Cotton, 40% Polyester <br>\r\nPattern Solid <br>\r\nFit type Regular Fit <br>\r\nSleeve type Short Sleeve <br>\r\nCollar style Classic Collar <br>\r\nLength Standard Length <br>\r\nCountr', 't-shirt', 'men', 'Amazon Brand - Symbol Store', 'https://m.media-amazon.com/images/I/714zCgmX+JL._SY550_.jpg', 9),
(43, 'Lymio Men T-Shirt || T-Shirt for Men || Plain T Shirt || T-Shirt (Polo-18-21)', 379, 'Material composition Cotton Blend <br>\r\nPattern Solid <br>\r\nFit type Regular Fit <br>\r\nSleeve type Half Sleeve <br>\r\nCollar style Collarless <br>\r\nLength Standard Length <br>\r\nCountry of Origin India ', 't-shirt', 'men', 'Lymio Store', 'https://m.media-amazon.com/images/I/71x4rLhMkML._SY550_.jpg', 10),
(44, 'Lymio Men T-Shirt || T-Shirt for Men || Plain T Shirt || T-Shirt (Polo-18-21)', 379, 'Material composition Cotton Blend <br>\r\nPattern Solid <br>\r\nFit type Regular Fit <br>\r\nSleeve type Half Sleeve <br>\r\nCollar style Collarless <br>\r\nLength Standard Length <br>\r\nCountry of Origin India ', 't-shirt', 'men', 'Lymio Store', 'https://m.media-amazon.com/images/I/71Jukhvw8DL._SY550_.jpg', 10),
(45, 'Lymio Men T-Shirt || T-Shirt for Men || Plain T Shirt || T-Shirt (Polo-18-21)', 379, 'Material composition Cotton Blend <br>\r\nPattern Solid <br>\r\nFit type Regular Fit <br>\r\nSleeve type Half Sleeve <br>\r\nCollar style Collarless <br>\r\nLength Standard Length <br>\r\nCountry of Origin India ', 't-shirt', 'men', 'Lymio Store', 'https://m.media-amazon.com/images/I/71G70WFtnaL._SY550_.jpg', 10),
(46, 'Lymio Men T-Shirt || T-Shirt for Men || Plain T Shirt || T-Shirt (Polo-18-21)', 379, 'Material composition Cotton Blend <br>\r\nPattern Solid <br>\r\nFit type Regular Fit <br>\r\nSleeve type Half Sleeve <br>\r\nCollar style Collarless <br>\r\nLength Standard Length <br>\r\nCountry of Origin India ', 't-shirt', 'men', 'Lymio Store', 'https://m.media-amazon.com/images/I/71SAYrGnadL._SY550_.jpg', 10),
(47, 'LEOTUDE Men Regular Fit Cottonblend Full Sleeve Textured Solid T-Shirt for Men (Color Grey)', 298, 'Material composition Cottonblend <br>\r\nPattern Textured <br>\r\nFit type Regular Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Round Collar <br>\r\nLength Standard Length <br>\r\nCountry of Origin In', 't-shirt', 'men', 'LEOTUDE Store', 'https://m.media-amazon.com/images/I/61jMkD48ZqL._SY550_.jpg', 11),
(48, 'LEOTUDE Men Regular Fit Cottonblend Full Sleeve Textured Solid T-Shirt for Men (Color Grey)', 298, 'Material composition Cottonblend <br>\r\nPattern Textured <br>\r\nFit type Regular Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Round Collar <br>\r\nLength Standard Length <br>\r\nCountry of Origin In', 't-shirt', 'men', 'LEOTUDE Store', 'https://m.media-amazon.com/images/I/61gAIVZ8wVL._SY550_.jpg', 11),
(49, 'LEOTUDE Men Regular Fit Cottonblend Full Sleeve Textured Solid T-Shirt for Men (Color Grey)', 298, 'Material composition Cottonblend <br>\r\nPattern Textured <br>\r\nFit type Regular Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Round Collar <br>\r\nLength Standard Length <br>\r\nCountry of Origin In', 't-shirt', 'men', 'LEOTUDE Store', 'https://m.media-amazon.com/images/I/71I56I4f1FL._SY550_.jpg', 11),
(50, 'BULLMER Black Trendy Front and Back Printed oversized Round Neck T-shirt for men', 299, 'Material composition Cottonblend <br>\r\nPattern Printed <br>\r\nFit type Regular Fit <br>\r\nSleeve type Half Sleeve <br>\r\nCollar style Club Collar <br>\r\nLength Standard Length <br>\r\nCountry of Origin Indi', 't-shirt', 'men', 'BULLMER Store', 'https://m.media-amazon.com/images/I/612Rl6GKHoL._SX466_.jpg', 12),
(51, 'BULLMER Black Trendy Front and Back Printed oversized Round Neck T-shirt for men', 299, 'Material composition Cottonblend <br>\r\nPattern Printed <br>\r\nFit type Regular Fit <br>\r\nSleeve type Half Sleeve <br>\r\nCollar style Club Collar <br>\r\nLength Standard Length <br>\r\nCountry of Origin Indi', 't-shirt', 'men', 'BULLMER Store', 'https://m.media-amazon.com/images/I/71tDWORaMVL._SX466_.jpg', 12),
(52, 'BULLMER Black Trendy Front and Back Printed oversized Round Neck T-shirt for men', 299, 'Material composition Cottonblend <br>\r\nPattern Printed <br>\r\nFit type Regular Fit <br>\r\nSleeve type Half Sleeve <br>\r\nCollar style Club Collar <br>\r\nLength Standard Length <br>\r\nCountry of Origin Indi', 't-shirt', 'men', 'BULLMER Store', 'https://m.media-amazon.com/images/I/61AkHLtfOAL._SX466_.jpg', 12),
(53, 'BULLMER Black Trendy Front and Back Printed oversized Round Neck T-shirt for men', 299, 'Material composition Cottonblend <br>\r\nPattern Printed <br>\r\nFit type Regular Fit <br>\r\nSleeve type Half Sleeve <br>\r\nCollar style Club Collar <br>\r\nLength Standard Length <br>\r\nCountry of Origin Indi', 't-shirt', 'men', 'BULLMER Store', 'https://m.media-amazon.com/images/I/61mkeIq7ciL._SX466_.jpg', 12),
(54, 'BULLMER Black Trendy Front and Back Printed oversized Round Neck T-shirt for men', 299, 'Material composition Cottonblend <br>\r\nPattern Printed <br>\r\nFit type Regular Fit <br>\r\nSleeve type Half Sleeve <br>\r\nCollar style Club Collar <br>\r\nLength Standard Length <br>\r\nCountry of Origin Indi', 't-shirt', 'men', 'BULLMER Store', 'https://m.media-amazon.com/images/I/71FxA9LOV1L._SX466_.jpg', 12),
(55, 'Symbol Premium Men Slim Fit Stretch Jeans (All Day Comfort)', 1599, 'Material type Cotton, Polyester and Lycra <br>\r\nLength Ankle length <br>\r\nStyle Classic <br>\r\nClosure type Button & Zip <br>\r\nOccasion type Casual <br>\r\nCare instructions Machine Wash <br>\r\nCountry of', 'jeans', 'men', 'Symbol Premium Store', 'https://m.media-amazon.com/images/I/81v9qR1csmL._SY550_.jpg', 13),
(56, 'Symbol Premium Men Slim Fit Stretch Jeans (All Day Comfort)', 1599, 'Material type Cotton, Polyester and Lycra <br>\r\nLength Ankle length <br>\r\nStyle Classic <br>\r\nClosure type Button & Zip <br>\r\nOccasion type Casual <br>\r\nCare instructions Machine Wash <br>\r\nCountry of', 'jeans', 'men', 'Symbol Premium Store', 'https://m.media-amazon.com/images/I/81Atrla9apL._SY550_.jpg', 13),
(57, 'Symbol Premium Men Slim Fit Stretch Jeans (All Day Comfort)', 1599, 'Material type Cotton, Polyester and Lycra <br>\r\nLength Ankle length <br>\r\nStyle Classic <br>\r\nClosure type Button & Zip <br>\r\nOccasion type Casual <br>\r\nCare instructions Machine Wash <br>\r\nCountry of', 'jeans', 'men', 'Symbol Premium Store', 'https://m.media-amazon.com/images/I/81qmjgxg4wL._SY550_.jpg', 13),
(58, 'Symbol Premium Men Slim Fit Stretch Jeans (All Day Comfort)', 1599, 'Material type Cotton, Polyester and Lycra <br>\r\nLength Ankle length <br>\r\nStyle Classic <br>\r\nClosure type Button & Zip <br>\r\nOccasion type Casual <br>\r\nCare instructions Machine Wash <br>\r\nCountry of', 'jeans', 'men', 'Symbol Premium Store', 'https://m.media-amazon.com/images/I/81aWYwrpwkL._SY550_.jpg', 13),
(59, 'Symbol Premium Men Slim Fit Stretch Jeans (All Day Comfort)', 1599, 'Material type Cotton, Polyester and Lycra <br>\r\nLength Ankle length <br>\r\nStyle Classic <br>\r\nClosure type Button & Zip <br>\r\nOccasion type Casual <br>\r\nCare instructions Machine Wash <br>\r\nCountry of', 'jeans', 'men', 'Symbol Premium Store', 'https://m.media-amazon.com/images/I/81WnsiT9vIL._SY550_.jpg', 13),
(60, 'Symbol Premium Men Slim Fit Selvedge Jeans (Cotton Stretch | Authentic & Crafted)', 1999, 'Material type Cotton and Lycra <br>\r\nLength Ankle length <br>\r\nStyle Classic <br>\r\nClosure type Button & Zip <br>\r\nOccasion type Smart Casual and Casual <br>\r\nCare instruction sMachine Wash <br>\r\nCoun', 'jeans', 'men', 'Symbol Premium Store', 'https://m.media-amazon.com/images/I/71h9Eqd+p+L._SY550_.jpg', 14),
(61, 'Symbol Premium Men Slim Fit Selvedge Jeans (Cotton Stretch | Authentic & Crafted)', 1999, 'Material type Cotton and Lycra <br>\r\nLength Ankle length <br>\r\nStyle Classic <br>\r\nClosure type Button & Zip <br>\r\nOccasion type Smart Casual and Casual <br>\r\nCare instruction sMachine Wash <br>\r\nCoun', 'jeans', 'men', 'Symbol Premium Store', 'https://m.media-amazon.com/images/I/61AnaipKjNL._SY550_.jpg', 14),
(62, 'Symbol Premium Men Slim Fit Selvedge Jeans (Cotton Stretch | Authentic & Crafted)', 1999, 'Material type Cotton and Lycra <br>\r\nLength Ankle length <br>\r\nStyle Classic <br>\r\nClosure type Button & Zip <br>\r\nOccasion type Smart Casual and Casual <br>\r\nCare instruction sMachine Wash <br>\r\nCoun', 'jeans', 'men', 'Symbol Premium Store', 'https://m.media-amazon.com/images/I/71O65fuXt2L._SY550_.jpg', 14),
(63, 'Amazon Brand - Symbol Men Cotton Rich Stretchable Jeans | Casual Denim Relaxed Fit', 699, 'Material type Cotton Blend <br>\r\nLength Standard Length <br>\r\nStyle Jeans <br>\r\nClosure type Button <br>\r\nOccasion type Casual <br>\r\nCare instructions Machine Wash <br>', 'jeans', 'men', 'Amazon Brand - Symbol Store', 'https://m.media-amazon.com/images/I/81eEVa-zFcL._SY550_.jpg', 15),
(64, 'Amazon Brand - Symbol Men Cotton Rich Stretchable Jeans | Casual Denim Relaxed Fit', 699, 'Material type Cotton Blend <br>\r\nLength Standard Length <br>\r\nStyle Jeans <br>\r\nClosure type Button <br>\r\nOccasion type Casual <br>\r\nCare instructions Machine Wash <br>', 'jeans', 'men', 'Amazon Brand - Symbol Store', 'https://m.media-amazon.com/images/I/81lxqAeV5bL._SY550_.jpg', 15),
(65, 'Amazon Brand - Symbol Men Cotton Rich Stretchable Jeans | Casual Denim Relaxed Fit', 699, 'Material type Cotton Blend <br>\r\nLength Standard Length <br>\r\nStyle Jeans <br>\r\nClosure type Button <br>\r\nOccasion type Casual <br>\r\nCare instructions Machine Wash <br>', 'jeans', 'men', 'Amazon Brand - Symbol Store', 'https://m.media-amazon.com/images/I/71yfMWj1oKL._SY550_.jpg', 15),
(66, 'Amazon Brand - Symbol Men Cotton Rich Stretchable Jeans | Casual Denim Relaxed Fit', 699, 'Material type Cotton Blend <br>\r\nLength Standard Length <br>\r\nStyle Jeans <br>\r\nClosure type Button <br>\r\nOccasion type Casual <br>\r\nCare instructions Machine Wash <br>', 'jeans', 'men', 'Amazon Brand - Symbol Store', 'https://m.media-amazon.com/images/I/71oExo9UO8L._SY550_.jpg', 15),
(67, 'Amazon Brand - Symbol Men Cotton Rich Stretchable Jeans | Casual Denim Relaxed Fit', 699, 'Material type Cotton Blend <br>\r\nLength Standard Length <br>\r\nStyle Jeans <br>\r\nClosure type Button <br>\r\nOccasion type Casual <br>\r\nCare instructions Machine Wash <br>', 'jeans', 'men', 'Amazon Brand - Symbol Store', 'https://m.media-amazon.com/images/I/71yywDdsF+L._SY550_.jpg', 15),
(68, 'Amazon Brand - Symbol Men Cotton Rich Stretchable Jeans | Casual Denim Relaxed Fit', 699, 'Material type Cotton Blend <br>\r\nLength Standard Length <br>\r\nStyle Jeans <br>\r\nClosure type Button <br>\r\nOccasion type Casual <br>\r\nCare instructions Machine Wash <br>', 'jeans', 'men', 'Amazon Brand - Symbol Store', 'https://m.media-amazon.com/images/I/71KQUt3HYRL._SY550_.jpg', 15),
(69, 'Ben Martin Men Relaxed Fit Jeans', 649, 'Material type Cotton <br>\r\nLength Full length <br>\r\nStyle Relaxed <br>\r\nClosure type Button <br>\r\nOccasion type Casual <br>\r\nCare instructions Do not bleach, dry in shade <br>\r\nCountry of Origin India', 'jeans', 'men', 'Ben Martin Store', 'https://m.media-amazon.com/images/I/616xchp1ECL._SY550_.jpg', 16),
(70, 'Ben Martin Men Relaxed Fit Jeans', 649, 'Material type Cotton <br>\r\nLength Full length <br>\r\nStyle Relaxed <br>\r\nClosure type Button <br>\r\nOccasion type Casual <br>\r\nCare instructions Do not bleach, dry in shade <br>\r\nCountry of Origin India', 'jeans', 'men', 'Ben Martin Store', 'https://m.media-amazon.com/images/I/61GqE4-jFNL._SX522_.jpg', 16),
(71, 'Ben Martin Men Relaxed Fit Jeans', 649, 'Material type Cotton <br>\r\nLength Full length <br>\r\nStyle Relaxed <br>\r\nClosure type Button <br>\r\nOccasion type Casual <br>\r\nCare instructions Do not bleach, dry in shade <br>\r\nCountry of Origin India', 'jeans', 'men', 'Ben Martin Store', 'https://m.media-amazon.com/images/I/71+u2xHHIBL._SY550_.jpg', 16),
(72, 'Ben Martin Men Relaxed Fit Jeans', 649, 'Material type Cotton <br>\r\nLength Full length <br>\r\nStyle Relaxed <br>\r\nClosure type Button <br>\r\nOccasion type Casual <br>\r\nCare instructions Do not bleach, dry in shade <br>\r\nCountry of Origin India', 'jeans', 'men', 'Ben Martin Store', 'https://m.media-amazon.com/images/I/61Tb-wMh6kL._SY550_.jpg', 16),
(73, 'Ben Martin Jeans for Men || Bootcut Jeans for Men || Wide Leg Jeans Men || Bell Bottom Jeans for Men', 749, 'Material type Cotton <br>\r\nLength Standard Length <br>\r\nStyle Retro <br>\r\nClosure type Button <br>\r\nOccasion type New Year, Bachelor Party, Anniversary, Birthday, Thanksgiving <br>\r\nCare instructions ', 'jeans', 'men', ' Ben Martin Store', 'https://m.media-amazon.com/images/I/41728tmoQmL._SY550_.jpg', 17),
(74, 'Ben Martin Jeans for Men || Bootcut Jeans for Men || Wide Leg Jeans Men || Bell Bottom Jeans for Men', 749, 'Material type Cotton <br>\r\nLength Standard Length <br>\r\nStyle Retro <br>\r\nClosure type Button <br>\r\nOccasion type New Year, Bachelor Party, Anniversary, Birthday, Thanksgiving <br>\r\nCare instructions ', 'jeans', 'men', ' Ben Martin Store', 'https://m.media-amazon.com/images/I/414+vZWdmtL._SX522_.jpg', 17),
(75, 'Ben Martin Jeans for Men || Bootcut Jeans for Men || Wide Leg Jeans Men || Bell Bottom Jeans for Men', 749, 'Material type Cotton <br>\r\nLength Standard Length <br>\r\nStyle Retro <br>\r\nClosure type Button <br>\r\nOccasion type New Year, Bachelor Party, Anniversary, Birthday, Thanksgiving <br>\r\nCare instructions ', 'jeans', 'men', ' Ben Martin Store', 'https://m.media-amazon.com/images/I/61Cc4ZlZC1L._SY550_.jpg', 17),
(76, 'Ben Martin Jeans for Men || Bootcut Jeans for Men || Wide Leg Jeans Men || Bell Bottom Jeans for Men', 749, 'Material type Cotton <br>\r\nLength Standard Length <br>\r\nStyle Retro <br>\r\nClosure type Button <br>\r\nOccasion type New Year, Bachelor Party, Anniversary, Birthday, Thanksgiving <br>\r\nCare instructions ', 'jeans', 'men', ' Ben Martin Store', 'https://m.media-amazon.com/images/I/61T4kySNarL._SY550_.jpg', 17),
(77, 'GRECIILOOKS Cotton Silk Women Saree', 549, 'Material composition COTTON SILK <br>\r\nWeave type Plain <br>\r\nOccasion type Festival, Party, Wedding <br>\r\nCare instructions Machine Wash <br>\r\nCountry of Origin India <br>', 'saree', 'women', ' GRECIILOOKS Store', 'https://m.media-amazon.com/images/I/71sJ7r87keL._SY550_.jpg', 18),
(78, 'GRECIILOOKS Cotton Silk Women Saree', 549, 'Material composition COTTON SILK <br>\r\nWeave type Plain <br>\r\nOccasion type Festival, Party, Wedding <br>\r\nCare instructions Machine Wash <br>\r\nCountry of Origin India <br>', 'saree', 'women', ' GRECIILOOKS Store', 'https://m.media-amazon.com/images/I/71wq2JnpGyL._SY550_.jpg', 18),
(79, 'GRECIILOOKS Cotton Silk Women Saree', 549, 'Material composition COTTON SILK <br>\r\nWeave type Plain <br>\r\nOccasion type Festival, Party, Wedding <br>\r\nCare instructions Machine Wash <br>\r\nCountry of Origin India <br>', 'saree', 'women', ' GRECIILOOKS Store', 'https://m.media-amazon.com/images/I/71D36YCV0hL._SY550_.jpg', 18),
(80, 'GRECIILOOKS Cotton Silk Women Saree', 549, 'Material composition COTTON SILK <br>\r\nWeave type Plain <br>\r\nOccasion type Festival, Party, Wedding <br>\r\nCare instructions Machine Wash <br>\r\nCountry of Origin India <br>', 'saree', 'women', ' GRECIILOOKS Store', 'https://m.media-amazon.com/images/I/71FBpY6pLoL._SY550_.jpg', 18),
(81, 'SWORNOF Women kanjivaram banarasi silk saree for festival Wedding silk with rich pallu Design saree', 899, 'Material composition Cotton linen <br>\r\nWeave type Kosa Silk <br>\r\nDesign name Printed <br>\r\nLength 5.5 mtr <br>\r\nOccasion type Dailywear, Durgapooja <br>\r\nCare instructions Dry Clean Only <br>\r\nCount', 'saree', 'women', 'SWORNOF Store', 'https://m.media-amazon.com/images/I/61OlJMyBvxS._SY550_.jpg', 19),
(82, 'SWORNOF Women kanjivaram banarasi silk saree for festival Wedding silk with rich pallu Design saree', 899, 'Material composition Cotton linen <br>\r\nWeave type Kosa Silk <br>\r\nDesign name Printed <br>\r\nLength 5.5 mtr <br>\r\nOccasion type Dailywear, Durgapooja <br>\r\nCare instructions Dry Clean Only <br>\r\nCount', 'saree', 'women', 'SWORNOF Store', 'https://m.media-amazon.com/images/I/71MJYHMQO+L._SY550_.jpg', 19),
(83, 'SWORNOF Women kanjivaram banarasi silk saree for festival Wedding silk with rich pallu Design saree', 899, 'Material composition Cotton linen <br>\r\nWeave type Kosa Silk <br>\r\nDesign name Printed <br>\r\nLength 5.5 mtr <br>\r\nOccasion type Dailywear, Durgapooja <br>\r\nCare instructions Dry Clean Only <br>\r\nCount', 'saree', 'women', 'SWORNOF Store', 'https://m.media-amazon.com/images/I/61X4OSUqm2L._SY550_.jpg', 19),
(84, 'SWORNOF Women kanjivaram banarasi silk saree for festival Wedding silk with rich pallu Design saree', 899, 'Material composition Cotton linen <br>\r\nWeave type Kosa Silk <br>\r\nDesign name Printed <br>\r\nLength 5.5 mtr <br>\r\nOccasion type Dailywear, Durgapooja <br>\r\nCare instructions Dry Clean Only <br>\r\nCount', 'saree', 'women', 'SWORNOF Store', 'https://m.media-amazon.com/images/I/81qsfu80paL._SY550_.jpg', 19),
(85, 'C J Enterprise Women Pure Kanjivaram Silk Saree Banarasi Silk Saree With Blouse Piece ', 489, 'Material compositionSoft Lichi Silk\r\nWeave type Jacquard <br>\r\nLength 6 yards <br>\r\nOccasion type Festival, Wedding, Party, Casual, Ceremony <br>\r\nPattern Embroidered <br>\r\nIncluded components With bl', 'saree', 'women', 'C J Enterprise', 'https://m.media-amazon.com/images/I/41ykC0f0VTL._SY500_.jpg', 20),
(86, 'C J Enterprise Women Pure Kanjivaram Silk Saree Banarasi Silk Saree With Blouse Piece ', 489, 'Material compositionSoft Lichi Silk\r\nWeave type Jacquard <br>\r\nLength 6 yards <br>\r\nOccasion type Festival, Wedding, Party, Casual, Ceremony <br>\r\nPattern Embroidered <br>\r\nIncluded components With bl', 'saree', 'women', 'C J Enterprise', 'https://m.media-amazon.com/images/I/515rreeMGfL._SY500_.jpg', 20),
(87, 'C J Enterprise Women Pure Kanjivaram Silk Saree Banarasi Silk Saree With Blouse Piece ', 489, 'Material compositionSoft Lichi Silk\r\nWeave type Jacquard <br>\r\nLength 6 yards <br>\r\nOccasion type Festival, Wedding, Party, Casual, Ceremony <br>\r\nPattern Embroidered <br>\r\nIncluded components With bl', 'saree', 'women', 'C J Enterprise', 'https://m.media-amazon.com/images/I/51rBEw-jXoL._SX385_.jpg', 20),
(88, 'C J Enterprise Women Pure Kanjivaram Silk Saree Banarasi Silk Saree With Blouse Piece ', 489, 'Material compositionSoft Lichi Silk\r\nWeave type Jacquard <br>\r\nLength 6 yards <br>\r\nOccasion type Festival, Wedding, Party, Casual, Ceremony <br>\r\nPattern Embroidered <br>\r\nIncluded components With bl', 'saree', 'women', 'C J Enterprise', 'https://m.media-amazon.com/images/I/517L0cQUn3L._SY500_.jpg', 20),
(89, 'C J Enterprise Women Pure Kanjivaram Silk Saree Banarasi Silk Saree With Blouse Piece ', 489, 'Material compositionSoft Lichi Silk\r\nWeave type Jacquard <br>\r\nLength 6 yards <br>\r\nOccasion type Festival, Wedding, Party, Casual, Ceremony <br>\r\nPattern Embroidered <br>\r\nIncluded components With bl', 'saree', 'women', 'C J Enterprise', 'https://m.media-amazon.com/images/I/61DgMGvWb7L._SY500_.jpg', 20),
(90, 'C J Enterprise Women Pure Kanjivaram Silk Saree Banarasi Silk Saree With Blouse Piece ', 489, 'Material compositionSoft Lichi Silk\r\nWeave type Jacquard <br>\r\nLength 6 yards <br>\r\nOccasion type Festival, Wedding, Party, Casual, Ceremony <br>\r\nPattern Embroidered <br>\r\nIncluded components With bl', 'saree', 'women', 'C J Enterprise', 'https://m.media-amazon.com/images/I/61DgMGvWb7L._SY500_.jpg', 20),
(91, 'Avantika Fashion Women Kanjivaram Soft Semi Silk Banarasi Sarees With Blouse Piece.', 489, 'Material composition Pure Silk <br>\r\nWeave type Banarasi <br>\r\nOccasion type Festival, Wedding <br>\r\nIncluded components With blouse piece <br>\r\nCare instructions Dry Clean Only <br>\r\nCountry of Origi', 'saree', 'women', 'Avantika Fashion', 'https://m.media-amazon.com/images/I/51F6f5n-2lL._SX385_.jpg', 21),
(92, 'Avantika Fashion Women Kanjivaram Soft Semi Silk Banarasi Sarees With Blouse Piece.', 489, 'Material composition Pure Silk <br>\r\nWeave type Banarasi <br>\r\nOccasion type Festival, Wedding <br>\r\nIncluded components With blouse piece <br>\r\nCare instructions Dry Clean Only <br>\r\nCountry of Origi', 'saree', 'women', 'Avantika Fashion', 'https://m.media-amazon.com/images/I/51AlZcBSF0L._SY500_.jpg', 21),
(93, 'Avantika Fashion Women Kanjivaram Soft Semi Silk Banarasi Sarees With Blouse Piece.', 1299, 'Material composition Kanjivaram Soft Cotton Linen Silk <br>\r\nWeave type Kanchipuram <br>\r\nOccasion type Festival <br>\r\nIncluded components With blouse piece <br>\r\nCare instruction sDry Clean Only <br>', 'saree', 'women', 'SGF11 Store', 'https://m.media-amazon.com/images/I/71N+YOY5vYL._SY550_.jpg', 22),
(94, 'SGF11 Women Kanjivaram Soft Cotton Linen Silk Saree With Unstitched Blouse Piece', 1299, 'Material composition Kanjivaram Soft Cotton Linen Silk <br>\r\nWeave type Kanchipuram <br>\r\nOccasion type Festival <br>\r\nIncluded components With blouse piece <br>\r\nCare instruction sDry Clean Only <br>', 'saree', 'women', 'SGF11 Store', 'https://m.media-amazon.com/images/I/71KXjE26mEL._SY550_.jpg', 22),
(95, 'SGF11 Women Kanjivaram Soft Cotton Linen Silk Saree With Unstitched Blouse Piece', 1299, 'Material composition Kanjivaram Soft Cotton Linen Silk <br>\r\nWeave type Kanchipuram <br>\r\nOccasion type Festival <br>\r\nIncluded components With blouse piece <br>\r\nCare instruction sDry Clean Only <br>', 'saree', 'women', 'SGF11 Store', 'https://m.media-amazon.com/images/I/71t3zccWo4L._SY550_.jpg', 22),
(96, 'SGF11 Women Kanjivaram Soft Cotton Linen Silk Saree With Unstitched Blouse Piece', 1299, 'Material composition Kanjivaram Soft Cotton Linen Silk <br>\r\nWeave type Kanchipuram <br>\r\nOccasion type Festival <br>\r\nIncluded components With blouse piece <br>\r\nCare instruction sDry Clean Only <br>', 'saree', 'women', 'SGF11 Store', 'https://m.media-amazon.com/images/I/71e63QqH8rL._SY550_.jpg', 22),
(97, 'MIRCHI FASHION Women Latest Chiffon Batik Printed Saree with Blouse Piece', 449, 'Material composition Chiffon <br>\r\nWeave type Plain <br>\r\nOccasion type Festival, Farewell, Wedding, Party, Evening <br>\r\nPattern Batik Block <br>\r\nCare instructions Machine Wash <br>\r\nCountry of Orig', 'saree', 'women', 'MIRCHI FASHION Store', 'https://m.media-amazon.com/images/I/81P3CCBY37L._SY550_.jpg', 23),
(98, 'MIRCHI FASHION Women Latest Chiffon Batik Printed Saree with Blouse Piece', 449, 'Material composition Chiffon <br>\r\nWeave type Plain <br>\r\nOccasion type Festival, Farewell, Wedding, Party, Evening <br>\r\nPattern Batik Block <br>\r\nCare instructions Machine Wash <br>\r\nCountry of Orig', 'saree', 'women', 'MIRCHI FASHION Store', 'https://m.media-amazon.com/images/I/81jdycG3M2L._SY550_.jpg', 23),
(99, 'MIRCHI FASHION Women Latest Chiffon Batik Printed Saree with Blouse Piece', 449, 'Material composition Chiffon <br>\r\nWeave type Plain <br>\r\nOccasion type Festival, Farewell, Wedding, Party, Evening <br>\r\nPattern Batik Block <br>\r\nCare instructions Machine Wash <br>\r\nCountry of Orig', 'saree', 'women', 'MIRCHI FASHION Store', 'https://m.media-amazon.com/images/I/81ooaEX4DHL._SY550_.jpg', 23),
(100, 'MIRCHI FASHION Women Latest Chiffon Batik Printed Saree with Blouse Piece', 449, 'Material composition Chiffon <br>\r\nWeave type Plain <br>\r\nOccasion type Festival, Farewell, Wedding, Party, Evening <br>\r\nPattern Batik Block <br>\r\nCare instructions Machine Wash <br>\r\nCountry of Orig', 'saree', 'women', 'MIRCHI FASHION Store', 'https://m.media-amazon.com/images/I/815bdyFLUwL._SY550_.jpg', 23),
(101, 'SIRIL Women Printed Silk Saree with Blouse', 299, 'Material composition Poly Silk <br>\r\nWeave type Plain <br>\r\nDesign name Solid <br>\r\nLength 6 yards <br>\r\nOccasion type Festive <br>\r\nPattern Traditional Prints <br>\r\nCountry of Origin India <br>', 'saree', 'women', ' SIRIL Store', 'https://m.media-amazon.com/images/I/71AMYn0kQfL._SY550_.jpg', 24),
(102, 'SIRIL Women Printed Silk Saree with Blouse', 299, 'Material composition Poly Silk <br>\r\nWeave type Plain <br>\r\nDesign name Solid <br>\r\nLength 6 yards <br>\r\nOccasion type Festive <br>\r\nPattern Traditional Prints <br>\r\nCountry of Origin India <br>', 'saree', 'women', ' SIRIL Store', 'https://m.media-amazon.com/images/I/71AMYn0kQfL._SY550_.jpg', 24),
(103, 'SIRIL Women Printed Silk Saree with Blouse', 299, 'Material composition Poly Silk <br>\r\nWeave type Plain <br>\r\nDesign name Solid <br>\r\nLength 6 yards <br>\r\nOccasion type Festive <br>\r\nPattern Traditional Prints <br>\r\nCountry of Origin India <br>', 'saree', 'women', ' SIRIL Store', 'https://m.media-amazon.com/images/I/71bzzppoQ0L._SY550_.jpg', 24),
(104, 'SIRIL Women Printed Silk Saree with Blouse', 299, 'Material composition Poly Silk <br>\r\nWeave type Plain <br>\r\nDesign name Solid <br>\r\nLength 6 yards <br>\r\nOccasion type Festive <br>\r\nPattern Traditional Prints <br>\r\nCountry of Origin India <br>', 'saree', 'women', ' SIRIL Store', 'https://m.media-amazon.com/images/I/71AYPbuBrhL._SY550_.jpg', 24),
(105, 'SAMAH Women Banarasi Silk Jacquard Saree with Unstitched Blouse Piece', 489, 'Material composition Silk <br>\r\nWeave type Jacquard <br>\r\nDesign name Zari <br>\r\nLength 6 yards <br>\r\nOccasion type Festival, Party, Evening, Casual, Ceremony <br>\r\nPattern Jacquard <br>\r\nCountry of O', 'saree', 'women', 'SAMAH\r\n', 'https://m.media-amazon.com/images/I/716brkjPo-L._SY550_.jpg', 25),
(106, 'SAMAH Women Banarasi Silk Jacquard Saree with Unstitched Blouse Piece', 489, 'Material composition Silk <br>\r\nWeave type Jacquard <br>\r\nDesign name Zari <br>\r\nLength 6 yards <br>\r\nOccasion type Festival, Party, Evening, Casual, Ceremony <br>\r\nPattern Jacquard <br>\r\nCountry of O', 'saree', 'women', 'SAMAH\r\n', 'https://m.media-amazon.com/images/I/71pqt7ifTWL._SY550_.jpg', 25),
(107, 'SAMAH Women Banarasi Silk Jacquard Saree with Unstitched Blouse Piece', 489, 'Material composition Silk <br>\r\nWeave type Jacquard <br>\r\nDesign name Zari <br>\r\nLength 6 yards <br>\r\nOccasion type Festival, Party, Evening, Casual, Ceremony <br>\r\nPattern Jacquard <br>\r\nCountry of O', 'saree', 'women', 'SAMAH\r\n', 'https://m.media-amazon.com/images/I/71Vd+jDUsPL._SY550_.jpg', 25),
(108, 'SAMAH Women Banarasi Silk Jacquard Saree with Unstitched Blouse Piece', 489, 'Material composition Silk <br>\r\nWeave type Jacquard <br>\r\nDesign name Zari <br>\r\nLength 6 yards <br>\r\nOccasion type Festival, Party, Evening, Casual, Ceremony <br>\r\nPattern Jacquard <br>\r\nCountry of O', 'saree', 'women', 'SAMAH\r\n', 'https://m.media-amazon.com/images/I/61C+HY7JLSL._SY550_.jpg', 25),
(109, 'Libas Fuchsia Yoke Design Silk Straight Kurta', 829, 'Material type Silk <br>\r\nFit type Straight <br>\r\nStyle Straight <br>\r\nCare instruction sHand Wash Only <br>\r\nAge range description Adult <br>\r\nSleeve type 3/4 Sleeve <br>\r\nCountry of Origin India <br>', 'kurti', 'women', 'Libas Store', 'https://m.media-amazon.com/images/I/61cA+WkivnL._SY550_.jpg', 26),
(110, 'Libas Fuchsia Yoke Design Silk Straight Kurta', 829, 'Material type Silk <br>\r\nFit type Straight <br>\r\nStyle Straight <br>\r\nCare instruction sHand Wash Only <br>\r\nAge range description Adult <br>\r\nSleeve type 3/4 Sleeve <br>\r\nCountry of Origin India <br>', 'kurti', 'women', 'Libas Store', 'https://m.media-amazon.com/images/I/61HyQafafkL._SY550_.jpg', 26),
(111, 'Libas Fuchsia Yoke Design Silk Straight Kurta', 829, 'Material type Silk <br>\r\nFit type Straight <br>\r\nStyle Straight <br>\r\nCare instruction sHand Wash Only <br>\r\nAge range description Adult <br>\r\nSleeve type 3/4 Sleeve <br>\r\nCountry of Origin India <br>', 'kurti', 'women', 'Libas Store', 'https://m.media-amazon.com/images/I/61Li-19vmNL._SY550_.jpg', 26),
(112, 'Libas Fuchsia Yoke Design Silk Straight Kurta', 829, 'Material type Silk <br>\r\nFit type Straight <br>\r\nStyle Straight <br>\r\nCare instructions Hand Wash Only <br>\r\nAge range description Adult <br>\r\nSleeve type 3/4 Sleeve <br>\r\nCountry of Origin India <br>', 'kurti', 'women', ' Libas Store', 'https://m.media-amazon.com/images/I/615QAm8nlzL._SY550_.jpg', 27),
(113, 'Libas Pink Printed Crepe Straight Kurta', 629, 'Material composition Blended <br>\r\nSleeve type Three-Quarter Sleeves <br>\r\nNeck style Sweet Heart Neck <br>\r\nPattern Printed <br>\r\nStyle Straight <br>\r\nCare instructions Hand Wash Only <br>\r\nCountry o', 'kurti', 'women', ' Libas Store', 'https://m.media-amazon.com/images/I/71eCCcRVGhL._SY550_.jpg', 28),
(114, 'Libas Multicoloured Printed Cotton Straight Kurta', 599, 'Material type Cotton <br>\r\nFit type Straight <br>\r\nStyle Straight <br>\r\nCare instructions Hand Wash Only <br> \r\nAge range description Adult <br>\r\nSleeve type Three-Quarter Sleeves <br>\r\nCountry of Ori', 'kurti', 'women', ' Libas Store', 'https://m.media-amazon.com/images/I/81aL6dW-kQL._SY550_.jpg', 29),
(115, 'Libas Magenta Yoke Design Rayon Straight Kurta', 899, 'Material composition Blended <br>\r\nSleeve type Three-Quarter Sleeves <br>\r\nNeck style Round Neck <br>\r\nPattern Yoke Design <br>\r\nStyle Straight <br>\r\nCare instructions Hand Wash Only <br>\r\nCountry of ', 'kurti', 'women', ' Libas Store', 'https://m.media-amazon.com/images/I/71ZTPuAgMML._SY550_.jpg', 29),
(116, 'GoSriKi Women Cotton Blend Straight Printed Kurta with Pant', 449, 'Material type Cotton Blend <br>\r\nFit type Regular <br>\r\nStyle Regular <br>\r\nClosure type Pull On <br>\r\nCare instructions Dry Clean Only <br>\r\nAge range description Adult <br>\r\nCountry of Origin India ', 'kurti', 'women', 'GoSriKi', 'https://m.media-amazon.com/images/I/61cTtzrqehL._SY550_.jpg', 30),
(117, 'FABNEX kurta set for women | Women Kurta | Women Kurta Sets Kurtis | Women Kurta Pant Set | Women Ku', 454, 'Material type Cotton Blend <br>\r\nFit type Regular <br>\r\nStyle Regular <br>\r\nClosure type Button <br>\r\nCare instructions Machine Wash <br>\r\nAge range description Adult <br>\r\nCountry of Origin India <br', 'kurti', 'women', 'FABNEX', 'https://m.media-amazon.com/images/I/51IG4UWlvoL._SY550_.jpg', 31),
(118, 'GoSriKi Women Rayon Blend Straight Printed Kurta with Pant & Dupatta', 689, 'Material composition Rayon-blend <br>\r\nLength Calf Length <br>\r\nSleeve type 3/4 Sleeve <br>\r\nNeck style Round Neck <br>\r\nStyle Regular <br>\r\nMaterial type Rayon Blend <br>\r\nCountry of Origin India <br', 'kurti', 'women', 'GoSriKi', 'https://m.media-amazon.com/images/I/61yF2fVlE6L._SX425_.jpg', 32),
(119, 'GoSriKi Women Rayon Blend Straight Printed Kurta with Pant & Dupatta', 689, 'Material composition Rayon-blend <br>\r\nLength Calf Length <br>\r\nSleeve type 3/4 Sleeve <br>\r\nNeck style Round Neck <br>\r\nStyle Regular <br>\r\nMaterial type Rayon Blend <br>\r\nCountry of Origin India <br', 'kurti', 'women', 'GoSriKi', 'https://m.media-amazon.com/images/I/61THDJab2wL._SX425_.jpg', 32),
(120, 'GoSriKi Women Rayon Blend Straight Printed Kurta with Pant & Dupatta', 689, 'Material composition Rayon-blend <br>\r\nLength Calf Length <br>\r\nSleeve type 3/4 Sleeve <br>\r\nNeck style Round Neck <br>\r\nStyle Regular <br>\r\nMaterial type Rayon Blend <br>\r\nCountry of Origin India <br', 'kurti', 'women', 'GoSriKi', 'https://m.media-amazon.com/images/I/61cOUi5572L._SX425_.jpg', 32),
(121, 'GoSriKi Women Rayon Blend Straight Printed Kurta with Pant & Dupatta', 689, 'Material composition Rayon-blend <br>\r\nLength Calf Length <br>\r\nSleeve type 3/4 Sleeve <br>\r\nNeck style Round Neck <br>\r\nStyle Regular <br>\r\nMaterial type Rayon Blend <br>\r\nCountry of Origin India <br', 'kurti', 'women', 'GoSriKi', 'https://m.media-amazon.com/images/I/61r99GrEgcL._SX425_.jpg', 32),
(122, 'GoSriKi Women Rayon Blend Straight Printed Kurta with Pant & Dupatta', 689, '', 'kurti', 'women', 'GoSriKi', 'https://m.media-amazon.com/images/I/610InQb9rTL._SX425_.jpg', 32),
(123, 'Yash Gallery Women Cotton Slub Sequin Work Angrakha Kurta for Women', 797, 'Material composition Cotton Slub <br>\r\nSleeve type 3/4 Sleeve <br>\r\nLength Calf Length <br>\r\nNeck style Mandarin Neck <br>\r\nPattern Solid <br>\r\nStyle Angrakha <br>\r\nCountry of Origin India <br>', 'kurti', 'women', 'Yash Gallery Store', 'https://m.media-amazon.com/images/I/81hWmLplfZL._SX425_.jpg', 33),
(124, 'Yash Gallery Women Cotton Slub Sequin Work Angrakha Kurta for Women', 797, 'Material composition Cotton Slub <br>\r\nSleeve type 3/4 Sleeve <br>\r\nLength Calf Length <br>\r\nNeck style Mandarin Neck <br>\r\nPattern Solid <br>\r\nStyle Angrakha <br>\r\nCountry of Origin India <br>', 'kurti', 'women', 'Yash Gallery Store', 'https://m.media-amazon.com/images/I/8151ifoqq7L._SX425_.jpg', 33),
(125, 'Yash Gallery Women Cotton Slub Sequin Work Angrakha Kurta for Women', 797, 'Material composition Cotton Slub <br>\r\nSleeve type 3/4 Sleeve <br>\r\nLength Calf Length <br>\r\nNeck style Mandarin Neck <br>\r\nPattern Solid <br>\r\nStyle Angrakha <br>\r\nCountry of Origin India <br>', 'kurti', 'women', 'Yash Gallery Store', 'https://m.media-amazon.com/images/I/71Ep9vopdyL._SY550_.jpg', 33);
INSERT INTO `product_details` (`product_id`, `product_name`, `product_price`, `product_description`, `product_category`, `product_gender`, `company_name`, `product_image`, `product_varient_id`) VALUES
(126, 'Yash Gallery Women Cotton Slub Sequin Work Angrakha Kurta for Women', 797, 'Material composition Cotton Slub <br>\r\nSleeve type 3/4 Sleeve <br>\r\nLength Calf Length <br>\r\nNeck style Mandarin Neck <br>\r\nPattern Solid <br>\r\nStyle Angrakha <br>\r\nCountry of Origin India <br>', 'kurti', 'women', 'Yash Gallery Store', 'https://m.media-amazon.com/images/I/61HCat3QbIL._SY550_.jpg', 33),
(127, 'Sun Fashion And Lifestyle Women Straight Printed Kurti with Crepe Lining', 499, 'Material type Organza,Crepe,Polyester <br>\r\nFit type Regular <br>\r\nStyle Regular <br>\r\nClosure type Pull On <br>\r\nCare instructions Machine Wash <br>\r\nAge range description Adult <br>\r\nCountry of Orig', 'kurti', 'women', ' Sun Fashion And Lifestyle Store', 'https://m.media-amazon.com/images/I/41ljS822pTL._SX385_.jpg', 34),
(128, 'Sun Fashion And Lifestyle Women Straight Printed Kurti with Crepe Lining', 499, 'Material type Organza,Crepe,Polyester <br>\r\nFit type Regular <br>\r\nStyle Regular <br>\r\nClosure type Pull On <br>\r\nCare instructions Machine Wash <br>\r\nAge range description Adult <br>\r\nCountry of Orig', 'kurti', 'women', ' Sun Fashion And Lifestyle Store', 'https://m.media-amazon.com/images/I/413brg04zCL._SY500_.jpg', 34),
(129, 'Sun Fashion And Lifestyle Women Straight Printed Kurti with Crepe Lining', 499, 'Material type Organza,Crepe,Polyester <br>\r\nFit type Regular <br>\r\nStyle Regular <br>\r\nClosure type Pull On <br>\r\nCare instructions Machine Wash <br>\r\nAge range description Adult <br>\r\nCountry of Orig', 'kurti', 'women', ' Sun Fashion And Lifestyle Store', 'https://m.media-amazon.com/images/I/5180D-gPXcL._SY500_.jpg', 34),
(130, 'Sun Fashion And Lifestyle Women Straight Printed Kurti with Crepe Lining', 499, 'Material type Organza,Crepe,Polyester <br>\r\nFit type Regular <br>\r\nStyle Regular <br>\r\nClosure type Pull On <br>\r\nCare instructions Machine Wash <br>\r\nAge range description Adult <br>\r\nCountry of Orig', 'kurti', 'women', ' Sun Fashion And Lifestyle Store', 'https://m.media-amazon.com/images/I/41z5jj+qTML._SX385_.jpg', 34),
(131, 'Sun Fashion And Lifestyle Women Straight Printed Kurti with Crepe Lining', 499, 'Material type Organza,Crepe,Polyester <br>\r\nFit type Regular <br>\r\nStyle Regular <br>\r\nClosure type Pull On <br>\r\nCare instructions Machine Wash <br>\r\nAge range description Adult <br>\r\nCountry of Orig', 'kurti', 'women', ' Sun Fashion And Lifestyle Store', 'https://m.media-amazon.com/images/I/51sprbA9p4L._SX425_.jpg', 34),
(132, 'Sun Fashion And Lifestyle Women Straight Printed Kurti with Crepe Lining', 499, 'Material type Organza,Crepe,Polyester <br>\r\nFit type Regular <br>\r\nStyle Regular <br>\r\nClosure type Pull On <br>\r\nCare instructions Machine Wash <br>\r\nAge range description Adult <br>\r\nCountry of Orig', 'kurti', 'women', ' Sun Fashion And Lifestyle Store', 'https://m.media-amazon.com/images/I/41xuV5iHEeL._SY500_.jpg', 34),
(133, 'DSK Studio Women Short Kurti', 242, 'Material type Organza,Crepe,Polyester <br>\r\nFit type Regular <br>\r\nStyle Regular <br>\r\nClosure type Pull On <br>\r\nCare instructions Machine Wash <br>\r\nAge range description Adult <br>\r\nCountry of Orig', 'kurti', 'women', 'DSK Studio', 'https://m.media-amazon.com/images/I/71f0yMcKbAL._SY550_.jpg', 35),
(134, 'DSK Studio Women Short Kurti', 242, 'Material type Organza,Crepe,Polyester <br>\r\nFit type Regular <br>\r\nStyle Regular <br>\r\nClosure type Pull On <br>\r\nCare instructions Machine Wash <br>\r\nAge range description Adult <br>\r\nCountry of Orig', 'kurti', 'women', 'DSK Studio', 'https://m.media-amazon.com/images/I/71MAES1faoL._SY550_.jpg', 35),
(135, 'DSK Studio Women Short Kurti', 242, 'Material type Organza,Crepe,Polyester <br>\r\nFit type Regular <br>\r\nStyle Regular <br>\r\nClosure type Pull On <br>\r\nCare instructions Machine Wash <br>\r\nAge range description Adult <br>\r\nCountry of Orig', 'kurti', 'women', 'DSK Studio', 'https://m.media-amazon.com/images/I/8136v9EIK4L._SY550_.jpg', 35),
(136, 'DSK Studio Women Short Kurti', 242, 'Material type Organza,Crepe,Polyester <br>\r\nFit type Regular <br>\r\nStyle Regular <br>\r\nClosure type Pull On <br>\r\nCare instructions Machine Wash <br>\r\nAge range description Adult <br>\r\nCountry of Orig', 'kurti', 'women', 'DSK Studio', 'https://m.media-amazon.com/images/I/81le+tJi7rL._SY550_.jpg', 35),
(137, 'BLOSSOM Womens Stretchable Cotton Hip Length T-Shirt with Round Hem & Raglan Sleeve_Hip Long Tee', 539, 'Material composition 80% Cotton, 20% Elastane <br>\r\nPattern Solid <br>\r\nFit type Regular Fit <br>\r\nSleeve type Raglan Sleeve <br>\r\nNeck style Crew Neck <br>\r\nStyle Western <br>\r\nCountry of Origin Indi', 'ladies_tshirt', 'women', 'BLOSSOM Store', 'https://m.media-amazon.com/images/I/41qutPtkVWL._SY500_.jpg', 36),
(138, 'BLOSSOM Womens Stretchable Cotton Hip Length T-Shirt with Round Hem & Raglan Sleeve_Hip Long Tee', 539, 'Material composition 80% Cotton, 20% Elastane <br>\r\nPattern Solid <br>\r\nFit type Regular Fit <br>\r\nSleeve type Raglan Sleeve <br>\r\nNeck style Crew Neck <br>\r\nStyle Western <br>\r\nCountry of Origin Indi', 'ladies_tshirt', 'women', 'BLOSSOM Store', 'https://m.media-amazon.com/images/I/51LOarwqzUL._SY500_.jpg', 36),
(139, 'BLOSSOM Womens Stretchable Cotton Hip Length T-Shirt with Round Hem & Raglan Sleeve_Hip Long Tee', 539, 'Material composition 80% Cotton, 20% Elastane <br>\r\nPattern Solid <br>\r\nFit type Regular Fit <br>\r\nSleeve type Raglan Sleeve <br>\r\nNeck style Crew Neck <br>\r\nStyle Western <br>\r\nCountry of Origin Indi', 'ladies_tshirt', 'women', 'BLOSSOM Store', 'https://m.media-amazon.com/images/I/41HSOwxvHTL._SY500_.jpg', 36),
(140, 'BLOSSOM Womens Stretchable Cotton Hip Length T-Shirt with Round Hem & Raglan Sleeve_Hip Long Tee', 539, 'Material composition 80% Cotton, 20% Elastane <br>\nPattern Solid <br>\nFit type Regular Fit <br>\nSleeve type Raglan Sleeve <br>\nNeck style Crew Neck <br>\nStyle Western <br>\nCountry of Origin Indi', 'ladies_tshirt', 'women', 'BLOSSOM Store', 'https://m.media-amazon.com/images/I/41CMdQoXQ1L._SY500_.jpg', 36),
(141, 'Amazon Brand - Symbol Women Cotton Stretch Half Sleeve Round Neck Regular Fit T-Shirt (Pack of 3)', 579, 'Material composition 80% Cotton, 20% Elastane <br>\nPattern Solid <br>\nFit type Regular Fit <br>\nSleeve type Raglan Sleeve <br>\nNeck style Crew Neck <br>\nStyle Western <br>\nCountry of Origin Indi', 'ladies_tshirt', 'women', 'Symbol Store', 'https://m.media-amazon.com/images/I/71DoG3w4U7L._SY550_.jpg', 37),
(142, 'Amazon Brand - Symbol Women Cotton Stretch Half Sleeve Round Neck Regular Fit T-Shirt (Pack of 3)', 579, 'Material composition 80% Cotton, 20% Elastane <br>\nPattern Solid <br>\nFit type Regular Fit <br>\nSleeve type Raglan Sleeve <br>\nNeck style Crew Neck <br>\nStyle Western <br>\nCountry of Origin Indi', 'ladies_tshirt', 'women', 'Symbol Store', 'https://m.media-amazon.com/images/I/81ZZNM1-kFL._SY550_.jpg', 37),
(143, 'Amazon Brand - Symbol Women Cotton Stretch Half Sleeve Round Neck Regular Fit T-Shirt (Pack of 3)', 579, 'Material composition 80% Cotton, 20% Elastane <br>\nPattern Solid <br>\nFit type Regular Fit <br>\nSleeve type Raglan Sleeve <br>\nNeck style Crew Neck <br>\nStyle Western <br>\nCountry of Origin India', 'ladies_tshirt', 'women', 'Symbol Store', 'https://m.media-amazon.com/images/I/81wy4xrkOXL._SY550_.jpg', 37),
(144, 'Amazon Brand - Symbol Women Cotton Stretch Half Sleeve Round Neck Regular Fit T-Shirt (Pack of 3)', 579, 'Material composition 80% Cotton, 20% Elastane <br>\nPattern Solid <br>\nFit type Regular Fit <br>\nSleeve type Raglan Sleeve <br>\nNeck style Crew Neck <br>\nStyle Western <br>\nCountry of Origin Indi', 'ladies_tshirt', 'women', 'Symbol Store', 'https://m.media-amazon.com/images/I/81Psi9DyuRL._SY550_.jpg', 37),
(145, 'RodZen Oversized | Loose Fit | Relaxed Fit | Wide Fit Half Sleeves 100% Cotton Round Neck Printed T-', 378, 'Material composition 100% Cotton <br>\r\nPattern Animal Print <br>\r\nFit type Loose Fit <br>\r\nSleeve type Half Sleeve <br>\r\nCollar style Collarless <br>\r\nLength Long Length <br>\r\nCountry of Origin India ', 'ladies_tshirt', 'women', 'RodZen Store', 'https://m.media-amazon.com/images/I/61rT+2kobdL._SY550_.jpg', 38),
(146, 'RodZen Oversized | Loose Fit | Relaxed Fit | Wide Fit Half Sleeves 100% Cotton Round Neck Printed T-', 378, 'Material composition 100% Cotton <br>\r\nPattern Animal Print <br>\r\nFit type Loose Fit <br>\r\nSleeve type Half Sleeve <br>\r\nCollar style Collarless <br>\r\nLength Long Length <br>\r\nCountry of Origin India ', 'ladies_tshirt', 'women', 'RodZen Store', 'https://m.media-amazon.com/images/I/81szHgUwlML._SY550_.jpg', 38),
(147, 'RodZen Oversized | Loose Fit | Relaxed Fit | Wide Fit Half Sleeves 100% Cotton Round Neck Printed T-', 378, 'Material composition 100% Cotton <br>\r\nPattern Animal Print <br>\r\nFit type Loose Fit <br>\r\nSleeve type Half Sleeve <br>\r\nCollar style Collarless <br>\r\nLength Long Length <br>\r\nCountry of Origin India ', 'ladies_tshirt', 'women', 'RodZen Store', 'https://m.media-amazon.com/images/I/71KeFZQy8cL._SY550_.jpg', 38),
(148, 'RodZen Oversized | Loose Fit | Relaxed Fit | Wide Fit Half Sleeves 100% Cotton Round Neck Printed T-', 378, 'Material composition 100% Cotton <br>\r\nPattern Animal Print <br>\r\nFit type Loose Fit <br>\r\nSleeve type Half Sleeve <br>\r\nCollar style Collarless <br>\r\nLength Long Length <br>\r\nCountry of Origin India ', 'ladies_tshirt', 'women', 'RodZen Store', 'https://m.media-amazon.com/images/I/71RshCYtnCL._SY550_.jpg', 38),
(149, 'Fabricorn Combo of Plain Color Stylish Up and Down Cotton Tshirt for women', 379, 'Material composition 100% Cotton <br>\r\nFit type Regular Fit <br>\r\nSleeve type Short Sleeve <br>\r\nCollar style Collarless <br>\r\nLength Standard length <br>\r\nNeck style Round Neck <br>\r\nCountry of Origi', 'ladies_tshirt', 'women', 'Fabricorn Store', 'https://m.media-amazon.com/images/I/614rKOTHPLL._SY550_.jpg', 39),
(150, 'Fabricorn Combo of Plain Color Stylish Up and Down Cotton Tshirt for women', 379, 'Material composition 100% Cotton <br>\r\nFit type Regular Fit <br>\r\nSleeve type Short Sleeve <br>\r\nCollar style Collarless <br>\r\nLength Standard length <br>\r\nNeck style Round Neck <br>\r\nCountry of Origi', 'ladies_tshirt', 'women', 'Fabricorn Store', 'https://m.media-amazon.com/images/I/51Ltp39Tp8S._SY550_.jpg', 39),
(151, 'Fabricorn Combo of Plain Color Stylish Up and Down Cotton Tshirt for women', 379, 'Material composition 100% Cotton <br>\r\nFit type Regular Fit <br>\r\nSleeve type Short Sleeve <br>\r\nCollar style Collarless <br>\r\nLength Standard length <br>\r\nNeck style Round Neck <br>\r\nCountry of Origi', 'ladies_tshirt', 'women', 'Fabricorn Store', 'https://m.media-amazon.com/images/I/61SdfC6V8fL._SY550_.jpg', 39),
(152, 'Fabricorn Combo of Plain Color Stylish Up and Down Cotton Tshirt for women', 379, 'Material composition 100% Cotton <br>\r\nFit type Regular Fit <br>\r\nSleeve type Short Sleeve <br>\r\nCollar style Collarless <br>\r\nLength Standard length <br>\r\nNeck style Round Neck <br>\r\nCountry of Origi', 'ladies_tshirt', 'women', 'Fabricorn Store', 'https://m.media-amazon.com/images/I/51yioiRtjDS._SY550_.jpg', 39),
(153, 'Fabricorn Combo of Plain Color Stylish Up and Down Cotton Tshirt for women', 379, 'Material composition 100% Cotton <br>\r\nFit type Regular Fit <br>\r\nSleeve type Short Sleeve <br>\r\nCollar style Collarless <br>\r\nLength Standard length <br>\r\nNeck style Round Neck <br>\r\nCountry of Origi', 'ladies_tshirt', 'women', 'Fabricorn Store', 'https://m.media-amazon.com/images/I/61tINIR34xL._SY550_.jpg', 39),
(154, 'Fabricorn Combo of Plain Color Stylish Up and Down Cotton Tshirt for women', 379, 'Material composition 100% Cotton <br>\r\nFit type Regular Fit <br>\r\nSleeve type Short Sleeve <br>\r\nCollar style Collarless <br>\r\nLength Standard length <br>\r\nNeck style Round Neck <br>\r\nCountry of Origi', 'ladies_tshirt', 'women', 'Fabricorn Store', 'https://m.media-amazon.com/images/I/5197jbKnfqL._SY550_.jpg', 39),
(155, 'JUNEBERRY Women Regular Fit T-Shirt', 299, 'Material composition 100% Cotton <br>\r\nPattern Floral <br>\r\nFit type Regular Fit <br>\r\nSleeve type Half Sleeve <br>\r\nCollar style Collarless <br>\r\nLengthS tandard Length <br>', 'ladies_tshirt', 'women', 'JUNEBERRY Store', 'https://m.media-amazon.com/images/I/61jiY0UYqyL._SX425_.jpg', 40),
(156, 'JUNEBERRY Women Regular Fit T-Shirt', 299, 'Material composition 100% Cotton <br>\r\nPattern Floral <br>\r\nFit type Regular Fit <br>\r\nSleeve type Half Sleeve <br>\r\nCollar style Collarless <br>\r\nLengthS tandard Length <br>', 'ladies_tshirt', 'women', 'JUNEBERRY Store', 'https://m.media-amazon.com/images/I/61Vn1fMPh7L._SX522_.jpg', 40),
(157, 'AUSK Women Regular Fit T-Shirt || Tshirt for Womens || Half Sleeve T Shirt for Female', 299, 'Material composition Cotton Blend <br>\r\nPattern Striped <br>\r\nFit type Regular Fit <br>\r\nSleeve type Short Sleeve <br>\r\nCollar style Collarless <br>\r\nLength Standard Length <br>\r\nCountry of Origin Ind', 'ladies_tshirt', 'women', 'AUSK Store', 'https://m.media-amazon.com/images/I/71baGj5T75L._SY550_.jpg', 41),
(158, 'AUSK Women Regular Fit T-Shirt || Tshirt for Womens || Half Sleeve T Shirt for Female', 299, 'Material composition Cotton Blend <br>\r\nPattern Striped <br>\r\nFit type Regular Fit <br>\r\nSleeve type Short Sleeve <br>\r\nCollar style Collarless <br>\r\nLength Standard Length <br>\r\nCountry of Origin Ind', 'ladies_tshirt', 'women', 'AUSK Store', 'https://m.media-amazon.com/images/I/71ScEuWDh-L._SY550_.jpg', 41),
(159, 'AUSK Women Regular Fit T-Shirt || Tshirt for Womens || Half Sleeve T Shirt for Female', 299, 'Material composition Cotton Blend <br>\r\nPattern Striped <br>\r\nFit type Regular Fit <br>\r\nSleeve type Short Sleeve <br>\r\nCollar style Collarless <br>\r\nLength Standard Length <br>\r\nCountry of Origin Ind', 'ladies_tshirt', 'women', 'AUSK Store', 'https://m.media-amazon.com/images/I/71GfqRIH2lL._SY550_.jpg', 41),
(160, 'AUSK Women Regular Fit T-Shirt || Tshirt for Womens || Half Sleeve T Shirt for Female', 299, 'Material composition Cotton Blend <br>\r\nPattern Striped <br>\r\nFit type Regular Fit <br>\r\nSleeve type Short Sleeve <br>\r\nCollar style Collarless <br>\r\nLength Standard Length <br>\r\nCountry of Origin Ind', 'ladies_tshirt', 'women', 'AUSK Store', 'https://m.media-amazon.com/images/I/71Y8zrpuCLL._SY550_.jpg', 41),
(161, 'AUSK Women Regular Fit T-Shirt || Tshirt for Womens || Half Sleeve T Shirt for Female', 299, 'Material composition Cotton Blend <br>\r\nPattern Striped <br>\r\nFit type Regular Fit <br>\r\nSleeve type Short Sleeve <br>\r\nCollar style Collarless <br>\r\nLength Standard Length <br>\r\nCountry of Origin Ind', 'ladies_tshirt', 'women', 'AUSK Store', 'https://m.media-amazon.com/images/I/71BxO1srpPL._SY550_.jpg', 41),
(162, 'AUSK Women Regular Fit T-Shirt || Tshirt for Womens || Half Sleeve T Shirt for Female', 299, 'Material composition Cotton Blend <br>\r\nPattern Striped <br>\r\nFit type Regular Fit <br>\r\nSleeve type Short Sleeve <br>\r\nCollar style Collarless <br>\r\nLength Standard Length <br>\r\nCountry of Origin Ind', 'ladies_tshirt', 'women', 'AUSK Store', 'https://m.media-amazon.com/images/I/71ZahuKQ9oL._SY550_.jpg', 41),
(163, 'FUNDAY FASHION Women Regular Fit Solid Casual Shirt', 358, 'Material composition Viscose Rayon <br>\r\nPattern Solid <br>\r\nFit type Oversized Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Club Collar <br>\r\nNeck style Collared Neck <br>\r\nCountry of Origin ', 'ladies_shirt', 'women', ' FUNDAY FASHION Store', 'https://m.media-amazon.com/images/I/61wwLxKN6gL._SY550_.jpg', 42),
(164, 'FUNDAY FASHION Women Regular Fit Solid Casual Shirt', 358, 'Material composition Viscose Rayon <br>\r\nPattern Solid <br>\r\nFit type Oversized Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Club Collar <br>\r\nNeck style Collared Neck <br>\r\nCountry of Origin ', 'ladies_shirt', 'women', ' FUNDAY FASHION Store', 'https://m.media-amazon.com/images/I/619XN2yOZmL._SX425_.jpg', 42),
(165, 'FUNDAY FASHION Women Regular Fit Solid Casual Shirt', 358, 'Material composition Viscose Rayon <br>\r\nPattern Solid <br>\r\nFit type Oversized Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Club Collar <br>\r\nNeck style Collared Neck <br>\r\nCountry of Origin ', 'ladies_shirt', 'women', ' FUNDAY FASHION Store', 'https://m.media-amazon.com/images/I/61bQ98yeWmL._SY550_.jpg', 42),
(166, 'FUNDAY FASHION Women Regular Fit Solid Casual Shirt', 358, 'Material composition Viscose Rayon <br>\r\nPattern Solid <br>\r\nFit type Oversized Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Club Collar <br>\r\nNeck style Collared Neck <br>\r\nCountry of Origin ', 'ladies_shirt', 'women', ' FUNDAY FASHION Store', 'https://m.media-amazon.com/images/I/61rnjnQrFtL._SY550_.jpg', 42),
(167, 'FUNDAY FASHION Women Regular Fit Solid Casual Shirt', 358, 'Material composition Viscose Rayon <br>\r\nPattern Solid <br>\r\nFit type Oversized Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Club Collar <br>\r\nNeck style Collared Neck <br>\r\nCountry of Origin ', 'ladies_shirt', 'women', ' FUNDAY FASHION Store', 'https://m.media-amazon.com/images/I/61ExXMjheLL._SX425_.jpg', 42),
(168, 'FUNDAY FASHION Women Regular Fit Solid Casual Shirt', 358, 'Material composition Viscose Rayon <br>\r\nPattern Solid <br>\r\nFit type Oversized Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Club Collar <br>\r\nNeck style Collared Neck <br>\r\nCountry of Origin ', 'ladies_shirt', 'women', ' FUNDAY FASHION Store', 'https://m.media-amazon.com/images/I/51WUNJfXhZL._SX425_.jpg', 42),
(169, 'FUNDAY FASHION Women Regular Fit Solid V Collered Casual Shirt', 297, 'Material composition Crepe <br>\r\nPattern Solid <br>\r\nFit type Regular Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Collared Neck <br>\r\nLength Standard Length <br>\r\nCountry of Origin India <br>', 'ladies_shirt', 'women', 'FUNDAY FASHION Store', 'https://m.media-amazon.com/images/I/51yiKNCTDlL._SX425_.jpg', 43),
(170, 'FUNDAY FASHION Women Regular Fit Solid V Collered Casual Shirt', 297, 'Material composition Crepe <br>\r\nPattern Solid <br>\r\nFit type Regular Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Collared Neck <br>\r\nLength Standard Length <br>\r\nCountry of Origin India <br>', 'ladies_shirt', 'women', 'FUNDAY FASHION Store', 'https://m.media-amazon.com/images/I/51jhzNAPXiL._SY550_.jpg', 43),
(171, 'FUNDAY FASHION Women Regular Fit Solid V Collered Casual Shirt', 297, 'Material composition Crepe <br>\r\nPattern Solid <br>\r\nFit type Regular Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Collared Neck <br>\r\nLength Standard Length <br>\r\nCountry of Origin India <br>', 'ladies_shirt', 'women', 'FUNDAY FASHION Store', 'https://m.media-amazon.com/images/I/51cvGACsOlL._SY550_.jpg', 43),
(172, 'FUNDAY FASHION Women Regular Fit Solid V Collered Casual Shirt', 297, 'Material composition Crepe <br>\r\nPattern Solid <br>\r\nFit type Regular Fit <br>\r\nSleeve type Long Sleeve <br>\r\nCollar style Collared Neck <br>\r\nLength Standard Length <br>\r\nCountry of Origin India <br>', 'ladies_shirt', 'women', 'FUNDAY FASHION Store', 'https://m.media-amazon.com/images/I/61b6mxjvpZL._SY550_.jpg', 43),
(173, 'Leriya Fashion Oversized Shirt for Women | Shirt for Women Stylish Western | Women Long Shirt', 397, 'Material composition85% POLY 15%COTTON\r\nFit type Regular Fit <br>\r\nSleeve type Half Sleeve <br>\r\nCollar style Camp Collar <br>\r\nLength Regular Length Not applicable for this attribute <br>\r\nNeck style', 'ladies_shirt', 'women', 'Leriya Fashion\r\n', 'https://m.media-amazon.com/images/I/71NR4MwqkjL._SY550_.jpg', 44),
(174, 'Leriya Fashion Oversized Shirt for Women | Shirt for Women Stylish Western | Women Long Shirt', 397, 'Material composition85% POLY 15%COTTON\r\nFit type Regular Fit <br>\r\nSleeve type Half Sleeve <br>\r\nCollar style Camp Collar <br>\r\nLength Regular Length Not applicable for this attribute <br>\r\nNeck style', 'ladies_shirt', 'women', 'Leriya Fashion\r\n', 'https://m.media-amazon.com/images/I/715NBtLT8fL._SY550_.jpg', 44),
(175, 'Leriya Fashion Women Regular Fit Shirt', 299, 'Material composition Crepe <br>\r\nFit type Regular Fit <br>\r\nSleeve type 3/4 Sleeve <br>\r\nCollar style Classic Collar <br>\r\nLength Regular <br>\r\nNeck style Collared Neck <br>\r\nCountry of Origin India <', 'ladies_shirt', 'women', 'Leriya Fashion', 'https://m.media-amazon.com/images/I/61RmXV-fzJL._SX522_.jpg', 45),
(176, 'Leriya Fashion Women Regular Fit Shirt', 299, 'Material composition Crepe <br>\r\nFit type Regular Fit <br>\r\nSleeve type 3/4 Sleeve <br>\r\nCollar style Classic Collar <br>\r\nLength Regular <br>\r\nNeck style Collared Neck <br>\r\nCountry of Origin India <', 'ladies_shirt', 'women', 'Leriya Fashion', 'https://m.media-amazon.com/images/I/51N46U50UyL._SY550_.jpg', 45),
(177, 'Leriya Fashion Women Regular Fit Shirt', 299, 'Material composition Crepe <br>\r\nFit type Regular Fit <br>\r\nSleeve type 3/4 Sleeve <br>\r\nCollar style Classic Collar <br>\r\nLength Regular <br>\r\nNeck style Collared Neck <br>\r\nCountry of Origin India <', 'ladies_shirt', 'women', 'Leriya Fashion', 'https://m.media-amazon.com/images/I/61vCtlF76qL._SY550_.jpg', 45),
(178, 'Leriya Fashion Women Regular Fit Shirt', 299, 'Material composition Crepe <br>\r\nFit type Regular Fit <br>\r\nSleeve type 3/4 Sleeve <br>\r\nCollar style Classic Collar <br>\r\nLength Regular <br>\r\nNeck style Collared Neck <br>\r\nCountry of Origin India <', 'ladies_shirt', 'women', 'Leriya Fashion', 'https://m.media-amazon.com/images/I/612Ebc8EiQL._SY550_.jpg', 45),
(179, 'Leriya Fashion Women Regular Fit Shirt', 299, 'Material composition Crepe <br>\r\nFit type Regular Fit <br>\r\nSleeve type 3/4 Sleeve <br>\r\nCollar style Classic Collar <br>\r\nLength Regular <br>\r\nNeck style Collared Neck <br>\r\nCountry of Origin India <', 'ladies_shirt', 'women', 'Leriya Fashion', 'https://m.media-amazon.com/images/I/61A4bKSgm4L._SY550_.jpg', 45),
(180, 'COTLAND Fashions Jaipuri Cotton Floral Printed Shaded Shirt for Women (Top Style)', 649, 'Material composition 100% Cotton <br>\r\nPattern Floral <br>\r\nFit type Classic Fit <br>\r\nSleeve type 3/4 Sleeve <br>\r\nCollar style Collarless <br>\r\nLength Long Length <br> \r\nCountry of Origin India <br>', 'ladies_shirt', 'women', 'COTLAND Fashions Store', 'https://m.media-amazon.com/images/I/81qIeCqiw2L._SY550_.jpg', 46),
(181, 'COTLAND Fashions Jaipuri Cotton Floral Printed Shaded Shirt for Women (Top Style)', 649, 'Material composition 100% Cotton <br>\r\nPattern Floral <br>\r\nFit type Classic Fit <br>\r\nSleeve type 3/4 Sleeve <br>\r\nCollar style Collarless <br>\r\nLength Long Length <br> \r\nCountry of Origin India <br>', 'ladies_shirt', 'women', 'COTLAND Fashions Store', 'https://m.media-amazon.com/images/I/81-GJANQqlL._SX466_.jpg', 46),
(182, 'COTLAND Fashions Jaipuri Cotton Floral Printed Shaded Shirt for Women (Top Style)', 649, 'Material composition 100% Cotton <br>\r\nPattern Floral <br>\r\nFit type Classic Fit <br>\r\nSleeve type 3/4 Sleeve <br>\r\nCollar style Collarless <br>\r\nLength Long Length <br> \r\nCountry of Origin India <br>', 'ladies_shirt', 'women', 'COTLAND Fashions Store', 'https://m.media-amazon.com/images/I/81KRWpa5XPL._SY550_.jpg', 46),
(183, 'COTLAND Fashions Jaipuri Cotton Floral Printed Shaded Shirt for Women (Top Style)', 649, 'Material composition 100% Cotton <br>\r\nPattern Floral <br>\r\nFit type Classic Fit <br>\r\nSleeve type 3/4 Sleeve <br>\r\nCollar style Collarless <br>\r\nLength Long Length <br> \r\nCountry of Origin India <br>', 'ladies_shirt', 'women', 'COTLAND Fashions Store', 'https://m.media-amazon.com/images/I/81AOrlw7sCL._SY550_.jpg', 46),
(184, 'COTLAND Fashions Jaipuri Cotton Floral Printed Shaded Shirt for Women (Top Style)', 649, 'Material composition 100% Cotton <br>\r\nPattern Floral <br>\r\nFit type Classic Fit <br>\r\nSleeve type 3/4 Sleeve <br>\r\nCollar style Collarless <br>\r\nLength Long Length <br> \r\nCountry of Origin India <br>', 'ladies_shirt', 'women', 'COTLAND Fashions Store', 'https://m.media-amazon.com/images/I/81IfzcXkrcL._SY550_.jpg', 46),
(185, 'ADBUCKS Womens High Rise Skinny Fit Jeans with Semi Elasticated Waistband', 840, 'Material type Cotton <br>\r\nLength Ankle Length <br>\r\nStyle Modern <br>\r\nClosure type Button <br>\r\nCare instructions Machine Wash <br>\r\nFit type Straight <br>\r\nCountry of Origin India <br>', 'ladies_jeans', 'women', 'ADBUCKS Store', 'https://m.media-amazon.com/images/I/51o5hYtCTYL._SY550_.jpg', 47),
(186, 'ADBUCKS Womens High Rise Skinny Fit Jeans with Semi Elasticated Waistband', 840, 'Material type Cotton <br>\r\nLength Ankle Length <br>\r\nStyle Modern <br>\r\nClosure type Button <br>\r\nCare instructions Machine Wash <br>\r\nFit type Straight <br>\r\nCountry of Origin India <br>', 'ladies_jeans', 'women', 'ADBUCKS Store', 'https://m.media-amazon.com/images/I/51Nl4mlofyL._SY550_.jpg', 47),
(187, 'ADBUCKS Womens High Rise Skinny Fit Jeans with Semi Elasticated Waistband', 840, 'Material type Cotton <br>\r\nLength Ankle Length <br>\r\nStyle Modern <br>\r\nClosure type Button <br>\r\nCare instructions Machine Wash <br>\r\nFit type Straight <br>\r\nCountry of Origin India <br>', 'ladies_jeans', 'women', 'ADBUCKS Store', 'https://m.media-amazon.com/images/I/71Oz+nYG3RL._SY550_.jpg', 47),
(188, 'ADBUCKS Womens High Rise Skinny Fit Jeans with Semi Elasticated Waistband', 840, 'Material type Cotton <br>\r\nLength Ankle Length <br>\r\nStyle Modern <br>\r\nClosure type Button <br>\r\nCare instructions Machine Wash <br>\r\nFit type Straight <br>\r\nCountry of Origin India <br>', 'ladies_jeans', 'women', 'ADBUCKS Store', 'https://m.media-amazon.com/images/I/61YmPGy6FaL._SY550_.jpg', 47),
(189, 'ADBUCKS Women Straight Fit High-Rise Jeans', 804, 'Material type Cotton <br>\r\nLength Ankle Length <br>\r\nStyle Modern <br>\r\nClosure type Button <br>\r\nCare instructions Machine Wash <br>\r\nFit type Straight <br>\r\nCountry of Origin India <br>', 'ladies_jeans', 'women', 'ADBUCKS Store', 'https://m.media-amazon.com/images/I/51RJryDCumL._SY500_.jpg', 48),
(190, 'ADBUCKS Women Straight Fit High-Rise Jeans', 804, 'Material type Cotton <br>\r\nLength Ankle Length <br>\r\nStyle Modern <br>\r\nClosure type Button <br>\r\nCare instructions Machine Wash <br>\r\nFit type Straight <br>\r\nCountry of Origin India <br>', 'ladies_jeans', 'women', 'ADBUCKS Store', 'https://m.media-amazon.com/images/I/4186WQH1lzL._SY500_.jpg', 48),
(191, 'ADBUCKS Women Straight Fit High-Rise Jeans', 804, 'Material type Cotton <br>\r\nLength Ankle Length <br>\r\nStyle Modern <br>\r\nClosure type Button <br>\r\nCare instructions Machine Wash <br>\r\nFit type Straight <br>\r\nCountry of Origin India <br>', 'ladies_jeans', 'women', 'ADBUCKS Store', 'https://m.media-amazon.com/images/I/51H0lO4mWDL._SY500_.jpg', 48),
(192, 'ADBUCKS Women Straight Fit High-Rise Jeans', 804, 'Material type Cotton <br>\r\nLength Ankle Length <br>\r\nStyle Modern <br>\r\nClosure type Button <br>\r\nCare instructions Machine Wash <br>\r\nFit type Straight <br>\r\nCountry of Origin India <br>', 'ladies_jeans', 'women', 'ADBUCKS Store', 'https://m.media-amazon.com/images/I/61z1XrYdg8L._SY500_.jpg', 48),
(193, 'Symbol Premium Women Skinny 4-Way Stretch Jeans (Mid Rise | Ankle Length | Desk-to-Dinner)', 1599, 'Material type Blended <br>\r\nLength Ankle-length <br> \r\nStyle Classic <br>\r\nClosure type Button & zip <br>\r\nOccasion type Formal and Smart Casual <br>\r\nCare instructions Machine Wash <br>\r\nCountry of O', 'ladies_jeans', 'women', 'Symbol Premium Store', 'https://m.media-amazon.com/images/I/6124EUeHjDL._SY550_.jpg', 49),
(194, 'Symbol Premium Women Skinny 4-Way Stretch Jeans (Mid Rise | Ankle Length | Desk-to-Dinner)', 1599, 'Material type Blended <br>\r\nLength Ankle-length <br> \r\nStyle Classic <br>\r\nClosure type Button & zip <br>\r\nOccasion type Formal and Smart Casual <br>\r\nCare instructions Machine Wash <br>\r\nCountry of O', 'ladies_jeans', 'women', 'Symbol Premium Store', 'https://m.media-amazon.com/images/I/61PkzM0hnEL._SY550_.jpg', 49),
(195, 'Symbol Premium Women Skinny 4-Way Stretch Jeans (Mid Rise | Ankle Length | Desk-to-Dinner)', 1599, 'Material type Blended <br>\r\nLength Ankle-length <br> \r\nStyle Classic <br>\r\nClosure type Button & zip <br>\r\nOccasion type Formal and Smart Casual <br>\r\nCare instructions Machine Wash <br>\r\nCountry of O', 'ladies_jeans', 'women', 'Symbol Premium Store', 'https://m.media-amazon.com/images/I/713LVwwVcSL._SY550_.jpg', 49),
(196, 'Symbol Premium Women Skinny 4-Way Stretch Jeans (Mid Rise | Ankle Length | Desk-to-Dinner)', 1599, 'Material type Blended <br>\r\nLength Ankle-length <br> \r\nStyle Classic <br>\r\nClosure type Button & zip <br>\r\nOccasion type Formal and Smart Casual <br>\r\nCare instructions Machine Wash <br>\r\nCountry of O', 'ladies_jeans', 'women', 'Symbol Premium Store', 'https://m.media-amazon.com/images/I/71ODjrA3j7L._SY550_.jpg', 49),
(197, 'Nifty Women Denim Wide Leg High Rise Jeans', 699, 'Material type Cotton Blend <br>\r\nStyle Retro <br>\r\nClosure type Button <br>\r\nCare instructions Machine Wash <br>\r\nFit type Relaxed <br>\r\nRise style High Rise <br>\r\nCountry of Origin India <br>', 'ladies_jeans', 'women', 'Nifty Store', 'https://m.media-amazon.com/images/I/61G6NdzVK8L._SY550_.jpg', 50),
(198, 'Nifty Women Denim Wide Leg High Rise Jeans', 699, 'Material type Cotton Blend <br>\r\nStyle Retro <br>\r\nClosure type Button <br>\r\nCare instructions Machine Wash <br>\r\nFit type Relaxed <br>\r\nRise style High Rise <br>\r\nCountry of Origin India <br>', 'ladies_jeans', 'women', 'Nifty Store', 'https://m.media-amazon.com/images/I/71MmdE5Be1L._SY550_.jpg', 50),
(199, 'Nifty Women Denim Wide Leg High Rise Jeans', 699, 'Material type Cotton Blend <br>\r\nStyle Retro <br>\r\nClosure type Button <br>\r\nCare instructions Machine Wash <br>\r\nFit type Relaxed <br>\r\nRise style High Rise <br>\r\nCountry of Origin India <br>', 'ladies_jeans', 'women', 'Nifty Store', 'https://m.media-amazon.com/images/I/81kKCHXlROL._SY550_.jpg', 50),
(200, 'KOTTY Women High Rise Relaxed Fit Cotton Lycra Blend Ankle Length Jeans', 580, 'Material type Cotton Blend <br>\r\nLength Full length <br>\r\nStyle Jeans <br>\r\nClosure type Button <br>\r\nOccasion type Casual <br>\r\nCare instructions Hand Wash Only <br>\r\nCountry of Origin India <br>', 'ladies_jeans', 'women', 'KOTTY Store\r\n', 'https://m.media-amazon.com/images/I/612+ZjkLFoL._SY550_.jpg', 51),
(201, 'KOTTY Women High Rise Relaxed Fit Cotton Lycra Blend Ankle Length Jeans', 580, 'Material type Cotton Blend <br>\r\nLength Full length <br>\r\nStyle Jeans <br>\r\nClosure type Button <br>\r\nOccasion type Casual <br>\r\nCare instructions Hand Wash Only <br>\r\nCountry of Origin India <br>', 'ladies_jeans', 'women', 'KOTTY Store\r\n', 'https://m.media-amazon.com/images/I/61-eglgl4rL._SY550_.jpg', 51),
(202, 'KOTTY Women High Rise Relaxed Fit Cotton Lycra Blend Ankle Length Jeans', 580, 'Material type Cotton Blend <br>\r\nLength Full length <br>\r\nStyle Jeans <br>\r\nClosure type Button <br>\r\nOccasion type Casual <br>\r\nCare instructions Hand Wash Only <br>\r\nCountry of Origin India <br>', 'ladies_jeans', 'women', 'KOTTY Store\r\n', 'https://m.media-amazon.com/images/I/71Qox1JaZeL._SY550_.jpg', 51),
(203, 'KOTTY Women High Rise Relaxed Fit Cotton Lycra Blend Ankle Length Jeans', 580, 'Material type Cotton Blend <br>\r\nLength Full length <br>\r\nStyle Jeans <br>\r\nClosure type Button <br>\r\nOccasion type Casual <br>\r\nCare instructions Hand Wash Only <br>\r\nCountry of Origin India <br>', 'ladies_jeans', 'women', 'KOTTY Store\r\n', 'https://m.media-amazon.com/images/I/61dL1N5hZ7L._SY550_.jpg', 51),
(204, 'KOTTY Women High Rise Relaxed Fit Cotton Lycra Blend Ankle Length Jeans', 580, 'Material type Cotton Blend <br>\r\nLength Full length <br>\r\nStyle Jeans <br>\r\nClosure type Button <br>\r\nOccasion type Casual <br>\r\nCare instructions Hand Wash Only <br>\r\nCountry of Origin India <br>', 'ladies_jeans', 'women', 'KOTTY Store\r\n', 'https://m.media-amazon.com/images/I/61UY0CyxUtL._SY550_.jpg', 51);

-- --------------------------------------------------------

--
-- Table structure for table `session`
--

CREATE TABLE `session` (
  `c_email` varchar(100) NOT NULL,
  `category` varchar(20) NOT NULL,
  `ip_address` varchar(40) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `session`
--

INSERT INTO `session` (`c_email`, `category`, `ip_address`) VALUES
('daluitapas@gmail.com', 'user', '::1');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `cart`
--
ALTER TABLE `cart`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `contact`
--
ALTER TABLE `contact`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `customer_details`
--
ALTER TABLE `customer_details`
  ADD PRIMARY KEY (`c_email`);

--
-- Indexes for table `customer_orders`
--
ALTER TABLE `customer_orders`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `product_details`
--
ALTER TABLE `product_details`
  ADD PRIMARY KEY (`product_id`);

--
-- Indexes for table `session`
--
ALTER TABLE `session`
  ADD PRIMARY KEY (`ip_address`),
  ADD UNIQUE KEY `c_email` (`c_email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `cart`
--
ALTER TABLE `cart`
  MODIFY `id` bigint(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=43;

--
-- AUTO_INCREMENT for table `contact`
--
ALTER TABLE `contact`
  MODIFY `id` bigint(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `customer_orders`
--
ALTER TABLE `customer_orders`
  MODIFY `id` bigint(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;

--
-- AUTO_INCREMENT for table `product_details`
--
ALTER TABLE `product_details`
  MODIFY `product_id` bigint(9) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=205;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
